// Code generated by "enumer -type=CUpti_ActivityThreadIdType -json"; DO NOT EDIT

package cupti

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityThreadIdType_name_0 = "CUPTI_ACTIVITY_THREAD_ID_TYPE_DEFAULTCUPTI_ACTIVITY_THREAD_ID_TYPE_SYSTEM"
	_CUpti_ActivityThreadIdType_name_1 = "CUPTI_ACTIVITY_THREAD_ID_TYPE_FORCE_INT"
)

var (
	_CUpti_ActivityThreadIdType_index_0 = [...]uint8{0, 37, 73}
	_CUpti_ActivityThreadIdType_index_1 = [...]uint8{0, 39}
)

func (i CUpti_ActivityThreadIdType) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _CUpti_ActivityThreadIdType_name_0[_CUpti_ActivityThreadIdType_index_0[i]:_CUpti_ActivityThreadIdType_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityThreadIdType_name_1
	default:
		return fmt.Sprintf("CUpti_ActivityThreadIdType(%d)", i)
	}
}

var _CUpti_ActivityThreadIdTypeNameToValue_map = map[string]CUpti_ActivityThreadIdType{
	_CUpti_ActivityThreadIdType_name_0[0:37]:  0,
	_CUpti_ActivityThreadIdType_name_0[37:73]: 1,
	_CUpti_ActivityThreadIdType_name_1[0:39]:  2147483647,
}

func CUpti_ActivityThreadIdTypeString(s string) (CUpti_ActivityThreadIdType, error) {
	if val, ok := _CUpti_ActivityThreadIdTypeNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityThreadIdType values", s)
}

func (i CUpti_ActivityThreadIdType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ActivityThreadIdType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityThreadIdType should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityThreadIdTypeString(s)
	return err
}
