// Code generated by "enumer -type=CUpti_ActivityKind -json"; DO NOT EDIT

package cupti

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityKind_name_0 = "CUPTI_ACTIVITY_KIND_INVALIDCUPTI_ACTIVITY_KIND_MEMCPYCUPTI_ACTIVITY_KIND_MEMSETCUPTI_ACTIVITY_KIND_KERNELCUPTI_ACTIVITY_KIND_DRIVERCUPTI_ACTIVITY_KIND_RUNTIMECUPTI_ACTIVITY_KIND_EVENTCUPTI_ACTIVITY_KIND_METRICCUPTI_ACTIVITY_KIND_DEVICECUPTI_ACTIVITY_KIND_CONTEXTCUPTI_ACTIVITY_KIND_CONCURRENT_KERNELCUPTI_ACTIVITY_KIND_NAMECUPTI_ACTIVITY_KIND_MARKERCUPTI_ACTIVITY_KIND_MARKER_DATACUPTI_ACTIVITY_KIND_SOURCE_LOCATORCUPTI_ACTIVITY_KIND_GLOBAL_ACCESSCUPTI_ACTIVITY_KIND_BRANCHCUPTI_ACTIVITY_KIND_OVERHEADCUPTI_ACTIVITY_KIND_CDP_KERNELCUPTI_ACTIVITY_KIND_PREEMPTIONCUPTI_ACTIVITY_KIND_ENVIRONMENTCUPTI_ACTIVITY_KIND_EVENT_INSTANCECUPTI_ACTIVITY_KIND_MEMCPY2CUPTI_ACTIVITY_KIND_METRIC_INSTANCECUPTI_ACTIVITY_KIND_INSTRUCTION_EXECUTIONCUPTI_ACTIVITY_KIND_UNIFIED_MEMORY_COUNTERCUPTI_ACTIVITY_KIND_FUNCTIONCUPTI_ACTIVITY_KIND_MODULECUPTI_ACTIVITY_KIND_DEVICE_ATTRIBUTECUPTI_ACTIVITY_KIND_SHARED_ACCESSCUPTI_ACTIVITY_KIND_PC_SAMPLINGCUPTI_ACTIVITY_KIND_PC_SAMPLING_RECORD_INFOCUPTI_ACTIVITY_KIND_INSTRUCTION_CORRELATIONCUPTI_ACTIVITY_KIND_OPENACC_DATACUPTI_ACTIVITY_KIND_OPENACC_LAUNCHCUPTI_ACTIVITY_KIND_OPENACC_OTHERCUPTI_ACTIVITY_KIND_CUDA_EVENTCUPTI_ACTIVITY_KIND_STREAMCUPTI_ACTIVITY_KIND_SYNCHRONIZATIONCUPTI_ACTIVITY_KIND_EXTERNAL_CORRELATIONCUPTI_ACTIVITY_KIND_NVLINKCUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENTCUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT_INSTANCECUPTI_ACTIVITY_KIND_INSTANTANEOUS_METRICCUPTI_ACTIVITY_KIND_INSTANTANEOUS_METRIC_INSTANCECUPTI_ACTIVITY_KIND_MEMORY"
	_CUpti_ActivityKind_name_1 = "CUPTI_ACTIVITY_KIND_FORCE_INT"
)

var (
	_CUpti_ActivityKind_index_0 = [...]uint16{0, 27, 53, 79, 105, 131, 158, 183, 209, 235, 262, 299, 323, 349, 380, 414, 447, 473, 501, 531, 561, 592, 626, 653, 688, 729, 771, 799, 825, 861, 894, 925, 968, 1011, 1043, 1077, 1110, 1140, 1166, 1201, 1241, 1267, 1306, 1354, 1394, 1443, 1469}
	_CUpti_ActivityKind_index_1 = [...]uint8{0, 29}
)

func (i CUpti_ActivityKind) String() string {
	switch {
	case 0 <= i && i <= 45:
		return _CUpti_ActivityKind_name_0[_CUpti_ActivityKind_index_0[i]:_CUpti_ActivityKind_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityKind_name_1
	default:
		return fmt.Sprintf("CUpti_ActivityKind(%d)", i)
	}
}

var _CUpti_ActivityKindNameToValue_map = map[string]CUpti_ActivityKind{
	_CUpti_ActivityKind_name_0[0:27]:      0,
	_CUpti_ActivityKind_name_0[27:53]:     1,
	_CUpti_ActivityKind_name_0[53:79]:     2,
	_CUpti_ActivityKind_name_0[79:105]:    3,
	_CUpti_ActivityKind_name_0[105:131]:   4,
	_CUpti_ActivityKind_name_0[131:158]:   5,
	_CUpti_ActivityKind_name_0[158:183]:   6,
	_CUpti_ActivityKind_name_0[183:209]:   7,
	_CUpti_ActivityKind_name_0[209:235]:   8,
	_CUpti_ActivityKind_name_0[235:262]:   9,
	_CUpti_ActivityKind_name_0[262:299]:   10,
	_CUpti_ActivityKind_name_0[299:323]:   11,
	_CUpti_ActivityKind_name_0[323:349]:   12,
	_CUpti_ActivityKind_name_0[349:380]:   13,
	_CUpti_ActivityKind_name_0[380:414]:   14,
	_CUpti_ActivityKind_name_0[414:447]:   15,
	_CUpti_ActivityKind_name_0[447:473]:   16,
	_CUpti_ActivityKind_name_0[473:501]:   17,
	_CUpti_ActivityKind_name_0[501:531]:   18,
	_CUpti_ActivityKind_name_0[531:561]:   19,
	_CUpti_ActivityKind_name_0[561:592]:   20,
	_CUpti_ActivityKind_name_0[592:626]:   21,
	_CUpti_ActivityKind_name_0[626:653]:   22,
	_CUpti_ActivityKind_name_0[653:688]:   23,
	_CUpti_ActivityKind_name_0[688:729]:   24,
	_CUpti_ActivityKind_name_0[729:771]:   25,
	_CUpti_ActivityKind_name_0[771:799]:   26,
	_CUpti_ActivityKind_name_0[799:825]:   27,
	_CUpti_ActivityKind_name_0[825:861]:   28,
	_CUpti_ActivityKind_name_0[861:894]:   29,
	_CUpti_ActivityKind_name_0[894:925]:   30,
	_CUpti_ActivityKind_name_0[925:968]:   31,
	_CUpti_ActivityKind_name_0[968:1011]:  32,
	_CUpti_ActivityKind_name_0[1011:1043]: 33,
	_CUpti_ActivityKind_name_0[1043:1077]: 34,
	_CUpti_ActivityKind_name_0[1077:1110]: 35,
	_CUpti_ActivityKind_name_0[1110:1140]: 36,
	_CUpti_ActivityKind_name_0[1140:1166]: 37,
	_CUpti_ActivityKind_name_0[1166:1201]: 38,
	_CUpti_ActivityKind_name_0[1201:1241]: 39,
	_CUpti_ActivityKind_name_0[1241:1267]: 40,
	_CUpti_ActivityKind_name_0[1267:1306]: 41,
	_CUpti_ActivityKind_name_0[1306:1354]: 42,
	_CUpti_ActivityKind_name_0[1354:1394]: 43,
	_CUpti_ActivityKind_name_0[1394:1443]: 44,
	_CUpti_ActivityKind_name_0[1443:1469]: 45,
	_CUpti_ActivityKind_name_1[0:29]:      2147483647,
}

func CUpti_ActivityKindString(s string) (CUpti_ActivityKind, error) {
	if val, ok := _CUpti_ActivityKindNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityKind values", s)
}

func (i CUpti_ActivityKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ActivityKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityKind should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityKindString(s)
	return err
}
