// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  cupti

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Event ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Event ) UnmarshalJSON([]byte) error { return nil }
func ( Event ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Event ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Event *Event

func ( events ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* events ) UnmarshalJSON([]byte) error { return nil }
func ( events ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* events ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_events *events
