// Code generated by "enumer -type=CUpti_ActivityPartitionedGlobalCacheConfig -json"; DO NOT EDIT

package cupti

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityPartitionedGlobalCacheConfig_name_0 = "CUPTI_ACTIVITY_PARTITIONED_GLOBAL_CACHE_CONFIG_UNKNOWNCUPTI_ACTIVITY_PARTITIONED_GLOBAL_CACHE_CONFIG_NOT_SUPPORTEDCUPTI_ACTIVITY_PARTITIONED_GLOBAL_CACHE_CONFIG_OFFCUPTI_ACTIVITY_PARTITIONED_GLOBAL_CACHE_CONFIG_ON"
	_CUpti_ActivityPartitionedGlobalCacheConfig_name_1 = "CUPTI_ACTIVITY_PARTITIONED_GLOBAL_CACHE_CONFIG_FORCE_INT"
)

var (
	_CUpti_ActivityPartitionedGlobalCacheConfig_index_0 = [...]uint8{0, 54, 114, 164, 213}
	_CUpti_ActivityPartitionedGlobalCacheConfig_index_1 = [...]uint8{0, 56}
)

func (i CUpti_ActivityPartitionedGlobalCacheConfig) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _CUpti_ActivityPartitionedGlobalCacheConfig_name_0[_CUpti_ActivityPartitionedGlobalCacheConfig_index_0[i]:_CUpti_ActivityPartitionedGlobalCacheConfig_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityPartitionedGlobalCacheConfig_name_1
	default:
		return fmt.Sprintf("CUpti_ActivityPartitionedGlobalCacheConfig(%d)", i)
	}
}

var _CUpti_ActivityPartitionedGlobalCacheConfigNameToValue_map = map[string]CUpti_ActivityPartitionedGlobalCacheConfig{
	_CUpti_ActivityPartitionedGlobalCacheConfig_name_0[0:54]:    0,
	_CUpti_ActivityPartitionedGlobalCacheConfig_name_0[54:114]:  1,
	_CUpti_ActivityPartitionedGlobalCacheConfig_name_0[114:164]: 2,
	_CUpti_ActivityPartitionedGlobalCacheConfig_name_0[164:213]: 3,
	_CUpti_ActivityPartitionedGlobalCacheConfig_name_1[0:56]:    2147483647,
}

func CUpti_ActivityPartitionedGlobalCacheConfigString(s string) (CUpti_ActivityPartitionedGlobalCacheConfig, error) {
	if val, ok := _CUpti_ActivityPartitionedGlobalCacheConfigNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityPartitionedGlobalCacheConfig values", s)
}

func (i CUpti_ActivityPartitionedGlobalCacheConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ActivityPartitionedGlobalCacheConfig) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityPartitionedGlobalCacheConfig should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityPartitionedGlobalCacheConfigString(s)
	return err
}
