// Code generated by "enumer -type=CUpti_EventDomainAttribute -json"; DO NOT EDIT

package cupti

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_EventDomainAttribute_name_0 = "CUPTI_EVENT_DOMAIN_ATTR_NAMECUPTI_EVENT_DOMAIN_ATTR_INSTANCE_COUNT"
	_CUpti_EventDomainAttribute_name_1 = "CUPTI_EVENT_DOMAIN_ATTR_TOTAL_INSTANCE_COUNTCUPTI_EVENT_DOMAIN_ATTR_COLLECTION_METHOD"
	_CUpti_EventDomainAttribute_name_2 = "CUPTI_EVENT_DOMAIN_ATTR_FORCE_INT"
)

var (
	_CUpti_EventDomainAttribute_index_0 = [...]uint8{0, 28, 66}
	_CUpti_EventDomainAttribute_index_1 = [...]uint8{0, 44, 85}
	_CUpti_EventDomainAttribute_index_2 = [...]uint8{0, 33}
)

func (i CUpti_EventDomainAttribute) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _CUpti_EventDomainAttribute_name_0[_CUpti_EventDomainAttribute_index_0[i]:_CUpti_EventDomainAttribute_index_0[i+1]]
	case 3 <= i && i <= 4:
		i -= 3
		return _CUpti_EventDomainAttribute_name_1[_CUpti_EventDomainAttribute_index_1[i]:_CUpti_EventDomainAttribute_index_1[i+1]]
	case i == 2147483647:
		return _CUpti_EventDomainAttribute_name_2
	default:
		return fmt.Sprintf("CUpti_EventDomainAttribute(%d)", i)
	}
}

var _CUpti_EventDomainAttributeNameToValue_map = map[string]CUpti_EventDomainAttribute{
	_CUpti_EventDomainAttribute_name_0[0:28]:  0,
	_CUpti_EventDomainAttribute_name_0[28:66]: 1,
	_CUpti_EventDomainAttribute_name_1[0:44]:  3,
	_CUpti_EventDomainAttribute_name_1[44:85]: 4,
	_CUpti_EventDomainAttribute_name_2[0:33]:  2147483647,
}

func CUpti_EventDomainAttributeString(s string) (CUpti_EventDomainAttribute, error) {
	if val, ok := _CUpti_EventDomainAttributeNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_EventDomainAttribute values", s)
}

func (i CUpti_EventDomainAttribute) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_EventDomainAttribute) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_EventDomainAttribute should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_EventDomainAttributeString(s)
	return err
}
