// Code generated by "enumer -type=CUpti_ActivityInstructionClass -json"; DO NOT EDIT

package cupti

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityInstructionClass_name_0 = "CUPTI_ACTIVITY_INSTRUCTION_CLASS_UNKNOWNCUPTI_ACTIVITY_INSTRUCTION_CLASS_FP_32CUPTI_ACTIVITY_INSTRUCTION_CLASS_FP_64CUPTI_ACTIVITY_INSTRUCTION_CLASS_INTEGERCUPTI_ACTIVITY_INSTRUCTION_CLASS_BIT_CONVERSIONCUPTI_ACTIVITY_INSTRUCTION_CLASS_CONTROL_FLOWCUPTI_ACTIVITY_INSTRUCTION_CLASS_GLOBALCUPTI_ACTIVITY_INSTRUCTION_CLASS_SHAREDCUPTI_ACTIVITY_INSTRUCTION_CLASS_LOCALCUPTI_ACTIVITY_INSTRUCTION_CLASS_GENERICCUPTI_ACTIVITY_INSTRUCTION_CLASS_SURFACECUPTI_ACTIVITY_INSTRUCTION_CLASS_CONSTANTCUPTI_ACTIVITY_INSTRUCTION_CLASS_TEXTURECUPTI_ACTIVITY_INSTRUCTION_CLASS_GLOBAL_ATOMICCUPTI_ACTIVITY_INSTRUCTION_CLASS_SHARED_ATOMICCUPTI_ACTIVITY_INSTRUCTION_CLASS_SURFACE_ATOMICCUPTI_ACTIVITY_INSTRUCTION_CLASS_INTER_THREAD_COMMUNICATIONCUPTI_ACTIVITY_INSTRUCTION_CLASS_BARRIERCUPTI_ACTIVITY_INSTRUCTION_CLASS_MISCELLANEOUSCUPTI_ACTIVITY_INSTRUCTION_CLASS_FP_16"
	_CUpti_ActivityInstructionClass_name_1 = "CUPTI_ACTIVITY_INSTRUCTION_CLASS_KIND_FORCE_INT"
)

var (
	_CUpti_ActivityInstructionClass_index_0 = [...]uint16{0, 40, 78, 116, 156, 203, 248, 287, 326, 364, 404, 444, 485, 525, 571, 617, 664, 723, 763, 809, 847}
	_CUpti_ActivityInstructionClass_index_1 = [...]uint8{0, 47}
)

func (i CUpti_ActivityInstructionClass) String() string {
	switch {
	case 0 <= i && i <= 19:
		return _CUpti_ActivityInstructionClass_name_0[_CUpti_ActivityInstructionClass_index_0[i]:_CUpti_ActivityInstructionClass_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityInstructionClass_name_1
	default:
		return fmt.Sprintf("CUpti_ActivityInstructionClass(%d)", i)
	}
}

var _CUpti_ActivityInstructionClassNameToValue_map = map[string]CUpti_ActivityInstructionClass{
	_CUpti_ActivityInstructionClass_name_0[0:40]:    0,
	_CUpti_ActivityInstructionClass_name_0[40:78]:   1,
	_CUpti_ActivityInstructionClass_name_0[78:116]:  2,
	_CUpti_ActivityInstructionClass_name_0[116:156]: 3,
	_CUpti_ActivityInstructionClass_name_0[156:203]: 4,
	_CUpti_ActivityInstructionClass_name_0[203:248]: 5,
	_CUpti_ActivityInstructionClass_name_0[248:287]: 6,
	_CUpti_ActivityInstructionClass_name_0[287:326]: 7,
	_CUpti_ActivityInstructionClass_name_0[326:364]: 8,
	_CUpti_ActivityInstructionClass_name_0[364:404]: 9,
	_CUpti_ActivityInstructionClass_name_0[404:444]: 10,
	_CUpti_ActivityInstructionClass_name_0[444:485]: 11,
	_CUpti_ActivityInstructionClass_name_0[485:525]: 12,
	_CUpti_ActivityInstructionClass_name_0[525:571]: 13,
	_CUpti_ActivityInstructionClass_name_0[571:617]: 14,
	_CUpti_ActivityInstructionClass_name_0[617:664]: 15,
	_CUpti_ActivityInstructionClass_name_0[664:723]: 16,
	_CUpti_ActivityInstructionClass_name_0[723:763]: 17,
	_CUpti_ActivityInstructionClass_name_0[763:809]: 18,
	_CUpti_ActivityInstructionClass_name_0[809:847]: 19,
	_CUpti_ActivityInstructionClass_name_1[0:47]:    2147483647,
}

func CUpti_ActivityInstructionClassString(s string) (CUpti_ActivityInstructionClass, error) {
	if val, ok := _CUpti_ActivityInstructionClassNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityInstructionClass values", s)
}

func (i CUpti_ActivityInstructionClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ActivityInstructionClass) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityInstructionClass should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityInstructionClassString(s)
	return err
}
