// Code generated by "enumer -type=CUpti_EventCollectionMode -json"; DO NOT EDIT

package cupti

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_EventCollectionMode_name_0 = "CUPTI_EVENT_COLLECTION_MODE_CONTINUOUSCUPTI_EVENT_COLLECTION_MODE_KERNEL"
	_CUpti_EventCollectionMode_name_1 = "CUPTI_EVENT_COLLECTION_MODE_FORCE_INT"
)

var (
	_CUpti_EventCollectionMode_index_0 = [...]uint8{0, 38, 72}
	_CUpti_EventCollectionMode_index_1 = [...]uint8{0, 37}
)

func (i CUpti_EventCollectionMode) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _CUpti_EventCollectionMode_name_0[_CUpti_EventCollectionMode_index_0[i]:_CUpti_EventCollectionMode_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_EventCollectionMode_name_1
	default:
		return fmt.Sprintf("CUpti_EventCollectionMode(%d)", i)
	}
}

var _CUpti_EventCollectionModeNameToValue_map = map[string]CUpti_EventCollectionMode{
	_CUpti_EventCollectionMode_name_0[0:38]:  0,
	_CUpti_EventCollectionMode_name_0[38:72]: 1,
	_CUpti_EventCollectionMode_name_1[0:37]:  2147483647,
}

func CUpti_EventCollectionModeString(s string) (CUpti_EventCollectionMode, error) {
	if val, ok := _CUpti_EventCollectionModeNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_EventCollectionMode values", s)
}

func (i CUpti_EventCollectionMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_EventCollectionMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_EventCollectionMode should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_EventCollectionModeString(s)
	return err
}
