// Code generated by "enumer -type=CUpti_MetricAttribute -json"; DO NOT EDIT

package cupti

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_MetricAttribute_name_0 = "CUPTI_METRIC_ATTR_NAMECUPTI_METRIC_ATTR_SHORT_DESCRIPTIONCUPTI_METRIC_ATTR_LONG_DESCRIPTIONCUPTI_METRIC_ATTR_CATEGORYCUPTI_METRIC_ATTR_VALUE_KINDCUPTI_METRIC_ATTR_EVALUATION_MODE"
	_CUpti_MetricAttribute_name_1 = "CUPTI_METRIC_ATTR_FORCE_INT"
)

var (
	_CUpti_MetricAttribute_index_0 = [...]uint8{0, 22, 57, 91, 117, 145, 178}
	_CUpti_MetricAttribute_index_1 = [...]uint8{0, 27}
)

func (i CUpti_MetricAttribute) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _CUpti_MetricAttribute_name_0[_CUpti_MetricAttribute_index_0[i]:_CUpti_MetricAttribute_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_MetricAttribute_name_1
	default:
		return fmt.Sprintf("CUpti_MetricAttribute(%d)", i)
	}
}

var _CUpti_MetricAttributeNameToValue_map = map[string]CUpti_MetricAttribute{
	_CUpti_MetricAttribute_name_0[0:22]:    0,
	_CUpti_MetricAttribute_name_0[22:57]:   1,
	_CUpti_MetricAttribute_name_0[57:91]:   2,
	_CUpti_MetricAttribute_name_0[91:117]:  3,
	_CUpti_MetricAttribute_name_0[117:145]: 4,
	_CUpti_MetricAttribute_name_0[145:178]: 5,
	_CUpti_MetricAttribute_name_1[0:27]:    2147483647,
}

func CUpti_MetricAttributeString(s string) (CUpti_MetricAttribute, error) {
	if val, ok := _CUpti_MetricAttributeNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_MetricAttribute values", s)
}

func (i CUpti_MetricAttribute) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_MetricAttribute) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_MetricAttribute should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_MetricAttributeString(s)
	return err
}
