package cupti

var DefaultActivities = []string{
	"CUPTI_ACTIVITY_KIND_MEMCPY",
	"CUPTI_ACTIVITY_KIND_MEMSET",
	"CUPTI_ACTIVITY_KIND_KERNEL",
	// "CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL",
	"CUPTI_ACTIVITY_KIND_OVERHEAD",
	"CUPTI_ACTIVITY_KIND_DRIVER",
	"CUPTI_ACTIVITY_KIND_RUNTIME",
}
