// Code generated by "enumer -type=CUpti_ActivityUnifiedMemoryCounterKind -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityUnifiedMemoryCounterKindName_0 = "CUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_UNKNOWNCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_BYTES_TRANSFER_HTODCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_BYTES_TRANSFER_DTOHCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_CPU_PAGE_FAULT_COUNTCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_GPU_PAGE_FAULTCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_THRASHINGCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_THROTTLINGCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_REMOTE_MAPCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_BYTES_TRANSFER_DTOD"
	_CUpti_ActivityUnifiedMemoryCounterKindName_1 = "CUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_FORCE_INT"
)

var (
	_CUpti_ActivityUnifiedMemoryCounterKindIndex_0 = [...]uint16{0, 50, 112, 174, 237, 294, 346, 399, 452, 514}
	_CUpti_ActivityUnifiedMemoryCounterKindIndex_1 = [...]uint8{0, 52}
)

func (i CUpti_ActivityUnifiedMemoryCounterKind) String() string {
	switch {
	case 0 <= i && i <= 8:
		return _CUpti_ActivityUnifiedMemoryCounterKindName_0[_CUpti_ActivityUnifiedMemoryCounterKindIndex_0[i]:_CUpti_ActivityUnifiedMemoryCounterKindIndex_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityUnifiedMemoryCounterKindName_1
	default:
		return fmt.Sprintf("CUpti_ActivityUnifiedMemoryCounterKind(%d)", i)
	}
}

var _CUpti_ActivityUnifiedMemoryCounterKindValues = []CUpti_ActivityUnifiedMemoryCounterKind{0, 1, 2, 3, 4, 5, 6, 7, 8, 2147483647}

var _CUpti_ActivityUnifiedMemoryCounterKindNameToValueMap = map[string]CUpti_ActivityUnifiedMemoryCounterKind{
	_CUpti_ActivityUnifiedMemoryCounterKindName_0[0:50]:    0,
	_CUpti_ActivityUnifiedMemoryCounterKindName_0[50:112]:  1,
	_CUpti_ActivityUnifiedMemoryCounterKindName_0[112:174]: 2,
	_CUpti_ActivityUnifiedMemoryCounterKindName_0[174:237]: 3,
	_CUpti_ActivityUnifiedMemoryCounterKindName_0[237:294]: 4,
	_CUpti_ActivityUnifiedMemoryCounterKindName_0[294:346]: 5,
	_CUpti_ActivityUnifiedMemoryCounterKindName_0[346:399]: 6,
	_CUpti_ActivityUnifiedMemoryCounterKindName_0[399:452]: 7,
	_CUpti_ActivityUnifiedMemoryCounterKindName_0[452:514]: 8,
	_CUpti_ActivityUnifiedMemoryCounterKindName_1[0:52]:    2147483647,
}

// CUpti_ActivityUnifiedMemoryCounterKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_ActivityUnifiedMemoryCounterKindString(s string) (CUpti_ActivityUnifiedMemoryCounterKind, error) {
	if val, ok := _CUpti_ActivityUnifiedMemoryCounterKindNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityUnifiedMemoryCounterKind values", s)
}

// CUpti_ActivityUnifiedMemoryCounterKindValues returns all values of the enum
func CUpti_ActivityUnifiedMemoryCounterKindValues() []CUpti_ActivityUnifiedMemoryCounterKind {
	return _CUpti_ActivityUnifiedMemoryCounterKindValues
}

// IsACUpti_ActivityUnifiedMemoryCounterKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_ActivityUnifiedMemoryCounterKind) IsACUpti_ActivityUnifiedMemoryCounterKind() bool {
	for _, v := range _CUpti_ActivityUnifiedMemoryCounterKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_ActivityUnifiedMemoryCounterKind
func (i CUpti_ActivityUnifiedMemoryCounterKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_ActivityUnifiedMemoryCounterKind
func (i *CUpti_ActivityUnifiedMemoryCounterKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityUnifiedMemoryCounterKind should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityUnifiedMemoryCounterKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_ActivityUnifiedMemoryCounterKind
func (i CUpti_ActivityUnifiedMemoryCounterKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_ActivityUnifiedMemoryCounterKind
func (i *CUpti_ActivityUnifiedMemoryCounterKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_ActivityUnifiedMemoryCounterKindString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_ActivityUnifiedMemoryCounterKind
func (i CUpti_ActivityUnifiedMemoryCounterKind) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_ActivityUnifiedMemoryCounterKind
func (i *CUpti_ActivityUnifiedMemoryCounterKind) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_ActivityUnifiedMemoryCounterKindString(s)
	return err
}

func (i CUpti_ActivityUnifiedMemoryCounterKind) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_ActivityUnifiedMemoryCounterKind) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_ActivityUnifiedMemoryCounterKindString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
