// Code generated by "enumer -type=CUpti_CallbackIdSync -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_CallbackIdSync_name_0 = "CUPTI_CBID_SYNCHRONIZE_INVALIDCUPTI_CBID_SYNCHRONIZE_STREAM_SYNCHRONIZEDCUPTI_CBID_SYNCHRONIZE_CONTEXT_SYNCHRONIZEDCUPTI_CBID_SYNCHRONIZE_SIZE"
	_CUpti_CallbackIdSync_name_1 = "CUPTI_CBID_SYNCHRONIZE_FORCE_INT"
)

var (
	_CUpti_CallbackIdSync_index_0 = [...]uint8{0, 30, 72, 115, 142}
	_CUpti_CallbackIdSync_index_1 = [...]uint8{0, 32}
)

func (i CUpti_CallbackIdSync) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _CUpti_CallbackIdSync_name_0[_CUpti_CallbackIdSync_index_0[i]:_CUpti_CallbackIdSync_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_CallbackIdSync_name_1
	default:
		return fmt.Sprintf("CUpti_CallbackIdSync(%d)", i)
	}
}

var _CUpti_CallbackIdSyncNameToValue_map = map[string]CUpti_CallbackIdSync{
	_CUpti_CallbackIdSync_name_0[0:30]:    0,
	_CUpti_CallbackIdSync_name_0[30:72]:   1,
	_CUpti_CallbackIdSync_name_0[72:115]:  2,
	_CUpti_CallbackIdSync_name_0[115:142]: 3,
	_CUpti_CallbackIdSync_name_1[0:32]:    2147483647,
}

func CUpti_CallbackIdSyncString(s string) (CUpti_CallbackIdSync, error) {
	if val, ok := _CUpti_CallbackIdSyncNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_CallbackIdSync values", s)
}

func (i CUpti_CallbackIdSync) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_CallbackIdSync) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_CallbackIdSync should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_CallbackIdSyncString(s)
	return err
}
