// Code generated by "enumer -type=CUpti_ActivityUnifiedMemoryCounterKind -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityUnifiedMemoryCounterKind_name_0 = "CUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_UNKNOWNCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_BYTES_TRANSFER_HTODCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_BYTES_TRANSFER_DTOHCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_CPU_PAGE_FAULT_COUNTCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_GPU_PAGE_FAULTCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_THRASHINGCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_THROTTLINGCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_REMOTE_MAPCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_BYTES_TRANSFER_DTOD"
	_CUpti_ActivityUnifiedMemoryCounterKind_name_1 = "CUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_KIND_FORCE_INT"
)

var (
	_CUpti_ActivityUnifiedMemoryCounterKind_index_0 = [...]uint16{0, 50, 112, 174, 237, 294, 346, 399, 452, 514}
	_CUpti_ActivityUnifiedMemoryCounterKind_index_1 = [...]uint8{0, 52}
)

func (i CUpti_ActivityUnifiedMemoryCounterKind) String() string {
	switch {
	case 0 <= i && i <= 8:
		return _CUpti_ActivityUnifiedMemoryCounterKind_name_0[_CUpti_ActivityUnifiedMemoryCounterKind_index_0[i]:_CUpti_ActivityUnifiedMemoryCounterKind_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityUnifiedMemoryCounterKind_name_1
	default:
		return fmt.Sprintf("CUpti_ActivityUnifiedMemoryCounterKind(%d)", i)
	}
}

var _CUpti_ActivityUnifiedMemoryCounterKindNameToValue_map = map[string]CUpti_ActivityUnifiedMemoryCounterKind{
	_CUpti_ActivityUnifiedMemoryCounterKind_name_0[0:50]:    0,
	_CUpti_ActivityUnifiedMemoryCounterKind_name_0[50:112]:  1,
	_CUpti_ActivityUnifiedMemoryCounterKind_name_0[112:174]: 2,
	_CUpti_ActivityUnifiedMemoryCounterKind_name_0[174:237]: 3,
	_CUpti_ActivityUnifiedMemoryCounterKind_name_0[237:294]: 4,
	_CUpti_ActivityUnifiedMemoryCounterKind_name_0[294:346]: 5,
	_CUpti_ActivityUnifiedMemoryCounterKind_name_0[346:399]: 6,
	_CUpti_ActivityUnifiedMemoryCounterKind_name_0[399:452]: 7,
	_CUpti_ActivityUnifiedMemoryCounterKind_name_0[452:514]: 8,
	_CUpti_ActivityUnifiedMemoryCounterKind_name_1[0:52]:    2147483647,
}

func CUpti_ActivityUnifiedMemoryCounterKindString(s string) (CUpti_ActivityUnifiedMemoryCounterKind, error) {
	if val, ok := _CUpti_ActivityUnifiedMemoryCounterKindNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityUnifiedMemoryCounterKind values", s)
}

func (i CUpti_ActivityUnifiedMemoryCounterKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ActivityUnifiedMemoryCounterKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityUnifiedMemoryCounterKind should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityUnifiedMemoryCounterKindString(s)
	return err
}
