// Code generated by "enumer -type=CUpti_ActivityAttribute -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityAttribute_name_0 = "CUPTI_ACTIVITY_ATTR_DEVICE_BUFFER_SIZECUPTI_ACTIVITY_ATTR_DEVICE_BUFFER_SIZE_CDPCUPTI_ACTIVITY_ATTR_DEVICE_BUFFER_POOL_LIMITCUPTI_ACTIVITY_ATTR_PROFILING_SEMAPHORE_POOL_SIZECUPTI_ACTIVITY_ATTR_PROFILING_SEMAPHORE_POOL_LIMIT"
	_CUpti_ActivityAttribute_name_1 = "CUPTI_ACTIVITY_ATTR_DEVICE_BUFFER_FORCE_INT"
)

var (
	_CUpti_ActivityAttribute_index_0 = [...]uint8{0, 38, 80, 124, 173, 223}
	_CUpti_ActivityAttribute_index_1 = [...]uint8{0, 43}
)

func (i CUpti_ActivityAttribute) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _CUpti_ActivityAttribute_name_0[_CUpti_ActivityAttribute_index_0[i]:_CUpti_ActivityAttribute_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityAttribute_name_1
	default:
		return fmt.Sprintf("CUpti_ActivityAttribute(%d)", i)
	}
}

var _CUpti_ActivityAttributeNameToValue_map = map[string]CUpti_ActivityAttribute{
	_CUpti_ActivityAttribute_name_0[0:38]:    0,
	_CUpti_ActivityAttribute_name_0[38:80]:   1,
	_CUpti_ActivityAttribute_name_0[80:124]:  2,
	_CUpti_ActivityAttribute_name_0[124:173]: 3,
	_CUpti_ActivityAttribute_name_0[173:223]: 4,
	_CUpti_ActivityAttribute_name_1[0:43]:    2147483647,
}

func CUpti_ActivityAttributeString(s string) (CUpti_ActivityAttribute, error) {
	if val, ok := _CUpti_ActivityAttributeNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityAttribute values", s)
}

func (i CUpti_ActivityAttribute) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ActivityAttribute) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityAttribute should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityAttributeString(s)
	return err
}
