// Code generated by "enumer -type=CUpti_ActivityEnvironmentKind -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityEnvironmentKindName_0 = "CUPTI_ACTIVITY_ENVIRONMENT_UNKNOWNCUPTI_ACTIVITY_ENVIRONMENT_SPEEDCUPTI_ACTIVITY_ENVIRONMENT_TEMPERATURECUPTI_ACTIVITY_ENVIRONMENT_POWERCUPTI_ACTIVITY_ENVIRONMENT_COOLING"
	_CUpti_ActivityEnvironmentKindName_1 = "CUPTI_ACTIVITY_ENVIRONMENT_KIND_FORCE_INT"
)

var (
	_CUpti_ActivityEnvironmentKindIndex_0 = [...]uint8{0, 34, 66, 104, 136, 170}
	_CUpti_ActivityEnvironmentKindIndex_1 = [...]uint8{0, 41}
)

func (i CUpti_ActivityEnvironmentKind) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _CUpti_ActivityEnvironmentKindName_0[_CUpti_ActivityEnvironmentKindIndex_0[i]:_CUpti_ActivityEnvironmentKindIndex_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityEnvironmentKindName_1
	default:
		return fmt.Sprintf("CUpti_ActivityEnvironmentKind(%d)", i)
	}
}

var _CUpti_ActivityEnvironmentKindValues = []CUpti_ActivityEnvironmentKind{0, 1, 2, 3, 4, 2147483647}

var _CUpti_ActivityEnvironmentKindNameToValueMap = map[string]CUpti_ActivityEnvironmentKind{
	_CUpti_ActivityEnvironmentKindName_0[0:34]:    0,
	_CUpti_ActivityEnvironmentKindName_0[34:66]:   1,
	_CUpti_ActivityEnvironmentKindName_0[66:104]:  2,
	_CUpti_ActivityEnvironmentKindName_0[104:136]: 3,
	_CUpti_ActivityEnvironmentKindName_0[136:170]: 4,
	_CUpti_ActivityEnvironmentKindName_1[0:41]:    2147483647,
}

// CUpti_ActivityEnvironmentKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_ActivityEnvironmentKindString(s string) (CUpti_ActivityEnvironmentKind, error) {
	if val, ok := _CUpti_ActivityEnvironmentKindNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityEnvironmentKind values", s)
}

// CUpti_ActivityEnvironmentKindValues returns all values of the enum
func CUpti_ActivityEnvironmentKindValues() []CUpti_ActivityEnvironmentKind {
	return _CUpti_ActivityEnvironmentKindValues
}

// IsACUpti_ActivityEnvironmentKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_ActivityEnvironmentKind) IsACUpti_ActivityEnvironmentKind() bool {
	for _, v := range _CUpti_ActivityEnvironmentKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_ActivityEnvironmentKind
func (i CUpti_ActivityEnvironmentKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_ActivityEnvironmentKind
func (i *CUpti_ActivityEnvironmentKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityEnvironmentKind should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityEnvironmentKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_ActivityEnvironmentKind
func (i CUpti_ActivityEnvironmentKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_ActivityEnvironmentKind
func (i *CUpti_ActivityEnvironmentKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_ActivityEnvironmentKindString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_ActivityEnvironmentKind
func (i CUpti_ActivityEnvironmentKind) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_ActivityEnvironmentKind
func (i *CUpti_ActivityEnvironmentKind) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_ActivityEnvironmentKindString(s)
	return err
}

func (i CUpti_ActivityEnvironmentKind) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_ActivityEnvironmentKind) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_ActivityEnvironmentKindString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
