// Code generated by "enumer -type=CUpti_ActivityUnifiedMemoryRemoteMapCause -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const _CUpti_ActivityUnifiedMemoryRemoteMapCause_name = "CUPTI_ACTIVITY_UNIFIED_MEMORY_REMOTE_MAP_CAUSE_UNKNOWNCUPTI_ACTIVITY_UNIFIED_MEMORY_REMOTE_MAP_CAUSE_COHERENCECUPTI_ACTIVITY_UNIFIED_MEMORY_REMOTE_MAP_CAUSE_THRASHINGCUPTI_ACTIVITY_UNIFIED_MEMORY_REMOTE_MAP_CAUSE_POLICYCUPTI_ACTIVITY_UNIFIED_MEMORY_REMOTE_MAP_CAUSE_OUT_OF_MEMORY"

var _CUpti_ActivityUnifiedMemoryRemoteMapCause_index = [...]uint16{0, 54, 110, 166, 219, 279}

func (i CUpti_ActivityUnifiedMemoryRemoteMapCause) String() string {
	if i < 0 || i >= CUpti_ActivityUnifiedMemoryRemoteMapCause(len(_CUpti_ActivityUnifiedMemoryRemoteMapCause_index)-1) {
		return fmt.Sprintf("CUpti_ActivityUnifiedMemoryRemoteMapCause(%d)", i)
	}
	return _CUpti_ActivityUnifiedMemoryRemoteMapCause_name[_CUpti_ActivityUnifiedMemoryRemoteMapCause_index[i]:_CUpti_ActivityUnifiedMemoryRemoteMapCause_index[i+1]]
}

var _CUpti_ActivityUnifiedMemoryRemoteMapCauseNameToValue_map = map[string]CUpti_ActivityUnifiedMemoryRemoteMapCause{
	_CUpti_ActivityUnifiedMemoryRemoteMapCause_name[0:54]:    0,
	_CUpti_ActivityUnifiedMemoryRemoteMapCause_name[54:110]:  1,
	_CUpti_ActivityUnifiedMemoryRemoteMapCause_name[110:166]: 2,
	_CUpti_ActivityUnifiedMemoryRemoteMapCause_name[166:219]: 3,
	_CUpti_ActivityUnifiedMemoryRemoteMapCause_name[219:279]: 4,
}

func CUpti_ActivityUnifiedMemoryRemoteMapCauseString(s string) (CUpti_ActivityUnifiedMemoryRemoteMapCause, error) {
	if val, ok := _CUpti_ActivityUnifiedMemoryRemoteMapCauseNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityUnifiedMemoryRemoteMapCause values", s)
}

func (i CUpti_ActivityUnifiedMemoryRemoteMapCause) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ActivityUnifiedMemoryRemoteMapCause) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityUnifiedMemoryRemoteMapCause should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityUnifiedMemoryRemoteMapCauseString(s)
	return err
}
