// Code generated by "enumer -type=CUpti_ActivityObjectKind -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityObjectKind_name_0 = "CUPTI_ACTIVITY_OBJECT_UNKNOWNCUPTI_ACTIVITY_OBJECT_PROCESSCUPTI_ACTIVITY_OBJECT_THREADCUPTI_ACTIVITY_OBJECT_DEVICECUPTI_ACTIVITY_OBJECT_CONTEXTCUPTI_ACTIVITY_OBJECT_STREAM"
	_CUpti_ActivityObjectKind_name_1 = "CUPTI_ACTIVITY_OBJECT_FORCE_INT"
)

var (
	_CUpti_ActivityObjectKind_index_0 = [...]uint8{0, 29, 58, 86, 114, 143, 171}
	_CUpti_ActivityObjectKind_index_1 = [...]uint8{0, 31}
)

func (i CUpti_ActivityObjectKind) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _CUpti_ActivityObjectKind_name_0[_CUpti_ActivityObjectKind_index_0[i]:_CUpti_ActivityObjectKind_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityObjectKind_name_1
	default:
		return fmt.Sprintf("CUpti_ActivityObjectKind(%d)", i)
	}
}

var _CUpti_ActivityObjectKindNameToValue_map = map[string]CUpti_ActivityObjectKind{
	_CUpti_ActivityObjectKind_name_0[0:29]:    0,
	_CUpti_ActivityObjectKind_name_0[29:58]:   1,
	_CUpti_ActivityObjectKind_name_0[58:86]:   2,
	_CUpti_ActivityObjectKind_name_0[86:114]:  3,
	_CUpti_ActivityObjectKind_name_0[114:143]: 4,
	_CUpti_ActivityObjectKind_name_0[143:171]: 5,
	_CUpti_ActivityObjectKind_name_1[0:31]:    2147483647,
}

func CUpti_ActivityObjectKindString(s string) (CUpti_ActivityObjectKind, error) {
	if val, ok := _CUpti_ActivityObjectKindNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityObjectKind values", s)
}

func (i CUpti_ActivityObjectKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ActivityObjectKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityObjectKind should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityObjectKindString(s)
	return err
}
