// Code generated by "enumer -type=CUpti_ActivityObjectKind -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityObjectKindName_0 = "CUPTI_ACTIVITY_OBJECT_UNKNOWNCUPTI_ACTIVITY_OBJECT_PROCESSCUPTI_ACTIVITY_OBJECT_THREADCUPTI_ACTIVITY_OBJECT_DEVICECUPTI_ACTIVITY_OBJECT_CONTEXTCUPTI_ACTIVITY_OBJECT_STREAM"
	_CUpti_ActivityObjectKindName_1 = "CUPTI_ACTIVITY_OBJECT_FORCE_INT"
)

var (
	_CUpti_ActivityObjectKindIndex_0 = [...]uint8{0, 29, 58, 86, 114, 143, 171}
	_CUpti_ActivityObjectKindIndex_1 = [...]uint8{0, 31}
)

func (i CUpti_ActivityObjectKind) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _CUpti_ActivityObjectKindName_0[_CUpti_ActivityObjectKindIndex_0[i]:_CUpti_ActivityObjectKindIndex_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityObjectKindName_1
	default:
		return fmt.Sprintf("CUpti_ActivityObjectKind(%d)", i)
	}
}

var _CUpti_ActivityObjectKindValues = []CUpti_ActivityObjectKind{0, 1, 2, 3, 4, 5, 2147483647}

var _CUpti_ActivityObjectKindNameToValueMap = map[string]CUpti_ActivityObjectKind{
	_CUpti_ActivityObjectKindName_0[0:29]:    0,
	_CUpti_ActivityObjectKindName_0[29:58]:   1,
	_CUpti_ActivityObjectKindName_0[58:86]:   2,
	_CUpti_ActivityObjectKindName_0[86:114]:  3,
	_CUpti_ActivityObjectKindName_0[114:143]: 4,
	_CUpti_ActivityObjectKindName_0[143:171]: 5,
	_CUpti_ActivityObjectKindName_1[0:31]:    2147483647,
}

// CUpti_ActivityObjectKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_ActivityObjectKindString(s string) (CUpti_ActivityObjectKind, error) {
	if val, ok := _CUpti_ActivityObjectKindNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityObjectKind values", s)
}

// CUpti_ActivityObjectKindValues returns all values of the enum
func CUpti_ActivityObjectKindValues() []CUpti_ActivityObjectKind {
	return _CUpti_ActivityObjectKindValues
}

// IsACUpti_ActivityObjectKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_ActivityObjectKind) IsACUpti_ActivityObjectKind() bool {
	for _, v := range _CUpti_ActivityObjectKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_ActivityObjectKind
func (i CUpti_ActivityObjectKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_ActivityObjectKind
func (i *CUpti_ActivityObjectKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityObjectKind should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityObjectKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_ActivityObjectKind
func (i CUpti_ActivityObjectKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_ActivityObjectKind
func (i *CUpti_ActivityObjectKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_ActivityObjectKindString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_ActivityObjectKind
func (i CUpti_ActivityObjectKind) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_ActivityObjectKind
func (i *CUpti_ActivityObjectKind) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_ActivityObjectKindString(s)
	return err
}

func (i CUpti_ActivityObjectKind) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_ActivityObjectKind) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_ActivityObjectKindString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
