// Code generated by "enumer -type=CUpti_ActivityUnifiedMemoryCounterScope -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityUnifiedMemoryCounterScope_name_0 = "CUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_SCOPE_UNKNOWNCUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_SCOPE_PROCESS_SINGLE_DEVICECUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_SCOPE_PROCESS_ALL_DEVICES"
	_CUpti_ActivityUnifiedMemoryCounterScope_name_1 = "CUPTI_ACTIVITY_UNIFIED_MEMORY_COUNTER_SCOPE_FORCE_INT"
)

var (
	_CUpti_ActivityUnifiedMemoryCounterScope_index_0 = [...]uint8{0, 51, 116, 179}
	_CUpti_ActivityUnifiedMemoryCounterScope_index_1 = [...]uint8{0, 53}
)

func (i CUpti_ActivityUnifiedMemoryCounterScope) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _CUpti_ActivityUnifiedMemoryCounterScope_name_0[_CUpti_ActivityUnifiedMemoryCounterScope_index_0[i]:_CUpti_ActivityUnifiedMemoryCounterScope_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityUnifiedMemoryCounterScope_name_1
	default:
		return fmt.Sprintf("CUpti_ActivityUnifiedMemoryCounterScope(%d)", i)
	}
}

var _CUpti_ActivityUnifiedMemoryCounterScopeNameToValue_map = map[string]CUpti_ActivityUnifiedMemoryCounterScope{
	_CUpti_ActivityUnifiedMemoryCounterScope_name_0[0:51]:    0,
	_CUpti_ActivityUnifiedMemoryCounterScope_name_0[51:116]:  1,
	_CUpti_ActivityUnifiedMemoryCounterScope_name_0[116:179]: 2,
	_CUpti_ActivityUnifiedMemoryCounterScope_name_1[0:53]:    2147483647,
}

func CUpti_ActivityUnifiedMemoryCounterScopeString(s string) (CUpti_ActivityUnifiedMemoryCounterScope, error) {
	if val, ok := _CUpti_ActivityUnifiedMemoryCounterScopeNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityUnifiedMemoryCounterScope values", s)
}

func (i CUpti_ActivityUnifiedMemoryCounterScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ActivityUnifiedMemoryCounterScope) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityUnifiedMemoryCounterScope should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityUnifiedMemoryCounterScopeString(s)
	return err
}
