// Code generated by "enumer -type=CUpti_ActivityComputeApiKind -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityComputeApiKindName_0 = "CUPTI_ACTIVITY_COMPUTE_API_UNKNOWNCUPTI_ACTIVITY_COMPUTE_API_CUDACUPTI_ACTIVITY_COMPUTE_API_CUDA_MPS"
	_CUpti_ActivityComputeApiKindName_1 = "CUPTI_ACTIVITY_COMPUTE_API_FORCE_INT"
)

var (
	_CUpti_ActivityComputeApiKindIndex_0 = [...]uint8{0, 34, 65, 100}
	_CUpti_ActivityComputeApiKindIndex_1 = [...]uint8{0, 36}
)

func (i CUpti_ActivityComputeApiKind) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _CUpti_ActivityComputeApiKindName_0[_CUpti_ActivityComputeApiKindIndex_0[i]:_CUpti_ActivityComputeApiKindIndex_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityComputeApiKindName_1
	default:
		return fmt.Sprintf("CUpti_ActivityComputeApiKind(%d)", i)
	}
}

var _CUpti_ActivityComputeApiKindValues = []CUpti_ActivityComputeApiKind{0, 1, 2, 2147483647}

var _CUpti_ActivityComputeApiKindNameToValueMap = map[string]CUpti_ActivityComputeApiKind{
	_CUpti_ActivityComputeApiKindName_0[0:34]:   0,
	_CUpti_ActivityComputeApiKindName_0[34:65]:  1,
	_CUpti_ActivityComputeApiKindName_0[65:100]: 2,
	_CUpti_ActivityComputeApiKindName_1[0:36]:   2147483647,
}

// CUpti_ActivityComputeApiKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_ActivityComputeApiKindString(s string) (CUpti_ActivityComputeApiKind, error) {
	if val, ok := _CUpti_ActivityComputeApiKindNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityComputeApiKind values", s)
}

// CUpti_ActivityComputeApiKindValues returns all values of the enum
func CUpti_ActivityComputeApiKindValues() []CUpti_ActivityComputeApiKind {
	return _CUpti_ActivityComputeApiKindValues
}

// IsACUpti_ActivityComputeApiKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_ActivityComputeApiKind) IsACUpti_ActivityComputeApiKind() bool {
	for _, v := range _CUpti_ActivityComputeApiKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_ActivityComputeApiKind
func (i CUpti_ActivityComputeApiKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_ActivityComputeApiKind
func (i *CUpti_ActivityComputeApiKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityComputeApiKind should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityComputeApiKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_ActivityComputeApiKind
func (i CUpti_ActivityComputeApiKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_ActivityComputeApiKind
func (i *CUpti_ActivityComputeApiKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_ActivityComputeApiKindString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_ActivityComputeApiKind
func (i CUpti_ActivityComputeApiKind) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_ActivityComputeApiKind
func (i *CUpti_ActivityComputeApiKind) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_ActivityComputeApiKindString(s)
	return err
}

func (i CUpti_ActivityComputeApiKind) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_ActivityComputeApiKind) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_ActivityComputeApiKindString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
