// Code generated by "enumer -type=CUpti_CallbackDomain -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_CallbackDomain_name_0 = "CUPTI_CB_DOMAIN_INVALIDCUPTI_CB_DOMAIN_DRIVER_APICUPTI_CB_DOMAIN_RUNTIME_APICUPTI_CB_DOMAIN_RESOURCECUPTI_CB_DOMAIN_SYNCHRONIZECUPTI_CB_DOMAIN_NVTXCUPTI_CB_DOMAIN_SIZE"
	_CUpti_CallbackDomain_name_1 = "CUPTI_CB_DOMAIN_FORCE_INT"
)

var (
	_CUpti_CallbackDomain_index_0 = [...]uint8{0, 23, 49, 76, 100, 127, 147, 167}
	_CUpti_CallbackDomain_index_1 = [...]uint8{0, 25}
)

func (i CUpti_CallbackDomain) String() string {
	switch {
	case 0 <= i && i <= 6:
		return _CUpti_CallbackDomain_name_0[_CUpti_CallbackDomain_index_0[i]:_CUpti_CallbackDomain_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_CallbackDomain_name_1
	default:
		return fmt.Sprintf("CUpti_CallbackDomain(%d)", i)
	}
}

var _CUpti_CallbackDomainNameToValue_map = map[string]CUpti_CallbackDomain{
	_CUpti_CallbackDomain_name_0[0:23]:    0,
	_CUpti_CallbackDomain_name_0[23:49]:   1,
	_CUpti_CallbackDomain_name_0[49:76]:   2,
	_CUpti_CallbackDomain_name_0[76:100]:  3,
	_CUpti_CallbackDomain_name_0[100:127]: 4,
	_CUpti_CallbackDomain_name_0[127:147]: 5,
	_CUpti_CallbackDomain_name_0[147:167]: 6,
	_CUpti_CallbackDomain_name_1[0:25]:    2147483647,
}

func CUpti_CallbackDomainString(s string) (CUpti_CallbackDomain, error) {
	if val, ok := _CUpti_CallbackDomainNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_CallbackDomain values", s)
}

func (i CUpti_CallbackDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_CallbackDomain) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_CallbackDomain should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_CallbackDomainString(s)
	return err
}
