// Code generated by "enumer -type=CUpti_ApiCallbackSite -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ApiCallbackSite_name_0 = "CUPTI_API_ENTERCUPTI_API_EXIT"
	_CUpti_ApiCallbackSite_name_1 = "CUPTI_API_CBSITE_FORCE_INT"
)

var (
	_CUpti_ApiCallbackSite_index_0 = [...]uint8{0, 15, 29}
	_CUpti_ApiCallbackSite_index_1 = [...]uint8{0, 26}
)

func (i CUpti_ApiCallbackSite) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _CUpti_ApiCallbackSite_name_0[_CUpti_ApiCallbackSite_index_0[i]:_CUpti_ApiCallbackSite_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_ApiCallbackSite_name_1
	default:
		return fmt.Sprintf("CUpti_ApiCallbackSite(%d)", i)
	}
}

var _CUpti_ApiCallbackSiteNameToValue_map = map[string]CUpti_ApiCallbackSite{
	_CUpti_ApiCallbackSite_name_0[0:15]:  0,
	_CUpti_ApiCallbackSite_name_0[15:29]: 1,
	_CUpti_ApiCallbackSite_name_1[0:26]:  2147483647,
}

func CUpti_ApiCallbackSiteString(s string) (CUpti_ApiCallbackSite, error) {
	if val, ok := _CUpti_ApiCallbackSiteNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ApiCallbackSite values", s)
}

func (i CUpti_ApiCallbackSite) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ApiCallbackSite) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ApiCallbackSite should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ApiCallbackSiteString(s)
	return err
}
