// Code generated by "enumer -type=CUpti_ActivitySynchronizationType -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivitySynchronizationTypeName_0 = "CUPTI_ACTIVITY_SYNCHRONIZATION_TYPE_UNKNOWNCUPTI_ACTIVITY_SYNCHRONIZATION_TYPE_EVENT_SYNCHRONIZECUPTI_ACTIVITY_SYNCHRONIZATION_TYPE_STREAM_WAIT_EVENTCUPTI_ACTIVITY_SYNCHRONIZATION_TYPE_STREAM_SYNCHRONIZECUPTI_ACTIVITY_SYNCHRONIZATION_TYPE_CONTEXT_SYNCHRONIZE"
	_CUpti_ActivitySynchronizationTypeName_1 = "CUPTI_ACTIVITY_SYNCHRONIZATION_TYPE_FORCE_INT"
)

var (
	_CUpti_ActivitySynchronizationTypeIndex_0 = [...]uint16{0, 43, 96, 149, 203, 258}
	_CUpti_ActivitySynchronizationTypeIndex_1 = [...]uint8{0, 45}
)

func (i CUpti_ActivitySynchronizationType) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _CUpti_ActivitySynchronizationTypeName_0[_CUpti_ActivitySynchronizationTypeIndex_0[i]:_CUpti_ActivitySynchronizationTypeIndex_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivitySynchronizationTypeName_1
	default:
		return fmt.Sprintf("CUpti_ActivitySynchronizationType(%d)", i)
	}
}

var _CUpti_ActivitySynchronizationTypeValues = []CUpti_ActivitySynchronizationType{0, 1, 2, 3, 4, 2147483647}

var _CUpti_ActivitySynchronizationTypeNameToValueMap = map[string]CUpti_ActivitySynchronizationType{
	_CUpti_ActivitySynchronizationTypeName_0[0:43]:    0,
	_CUpti_ActivitySynchronizationTypeName_0[43:96]:   1,
	_CUpti_ActivitySynchronizationTypeName_0[96:149]:  2,
	_CUpti_ActivitySynchronizationTypeName_0[149:203]: 3,
	_CUpti_ActivitySynchronizationTypeName_0[203:258]: 4,
	_CUpti_ActivitySynchronizationTypeName_1[0:45]:    2147483647,
}

// CUpti_ActivitySynchronizationTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_ActivitySynchronizationTypeString(s string) (CUpti_ActivitySynchronizationType, error) {
	if val, ok := _CUpti_ActivitySynchronizationTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivitySynchronizationType values", s)
}

// CUpti_ActivitySynchronizationTypeValues returns all values of the enum
func CUpti_ActivitySynchronizationTypeValues() []CUpti_ActivitySynchronizationType {
	return _CUpti_ActivitySynchronizationTypeValues
}

// IsACUpti_ActivitySynchronizationType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_ActivitySynchronizationType) IsACUpti_ActivitySynchronizationType() bool {
	for _, v := range _CUpti_ActivitySynchronizationTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_ActivitySynchronizationType
func (i CUpti_ActivitySynchronizationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_ActivitySynchronizationType
func (i *CUpti_ActivitySynchronizationType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivitySynchronizationType should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivitySynchronizationTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_ActivitySynchronizationType
func (i CUpti_ActivitySynchronizationType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_ActivitySynchronizationType
func (i *CUpti_ActivitySynchronizationType) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_ActivitySynchronizationTypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_ActivitySynchronizationType
func (i CUpti_ActivitySynchronizationType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_ActivitySynchronizationType
func (i *CUpti_ActivitySynchronizationType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_ActivitySynchronizationTypeString(s)
	return err
}

func (i CUpti_ActivitySynchronizationType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_ActivitySynchronizationType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_ActivitySynchronizationTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
