// Code generated by "enumer -type=CUpti_MetricValueKind -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_MetricValueKind_name_0 = "CUPTI_METRIC_VALUE_KIND_DOUBLECUPTI_METRIC_VALUE_KIND_UINT64CUPTI_METRIC_VALUE_KIND_PERCENTCUPTI_METRIC_VALUE_KIND_THROUGHPUTCUPTI_METRIC_VALUE_KIND_INT64CUPTI_METRIC_VALUE_KIND_UTILIZATION_LEVEL"
	_CUpti_MetricValueKind_name_1 = "CUPTI_METRIC_VALUE_KIND_FORCE_INT"
)

var (
	_CUpti_MetricValueKind_index_0 = [...]uint8{0, 30, 60, 91, 125, 154, 195}
	_CUpti_MetricValueKind_index_1 = [...]uint8{0, 33}
)

func (i CUpti_MetricValueKind) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _CUpti_MetricValueKind_name_0[_CUpti_MetricValueKind_index_0[i]:_CUpti_MetricValueKind_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_MetricValueKind_name_1
	default:
		return fmt.Sprintf("CUpti_MetricValueKind(%d)", i)
	}
}

var _CUpti_MetricValueKindNameToValue_map = map[string]CUpti_MetricValueKind{
	_CUpti_MetricValueKind_name_0[0:30]:    0,
	_CUpti_MetricValueKind_name_0[30:60]:   1,
	_CUpti_MetricValueKind_name_0[60:91]:   2,
	_CUpti_MetricValueKind_name_0[91:125]:  3,
	_CUpti_MetricValueKind_name_0[125:154]: 4,
	_CUpti_MetricValueKind_name_0[154:195]: 5,
	_CUpti_MetricValueKind_name_1[0:33]:    2147483647,
}

func CUpti_MetricValueKindString(s string) (CUpti_MetricValueKind, error) {
	if val, ok := _CUpti_MetricValueKindNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_MetricValueKind values", s)
}

func (i CUpti_MetricValueKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_MetricValueKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_MetricValueKind should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_MetricValueKindString(s)
	return err
}
