// Code generated by "enumer -type=CUpti_ActivityKind -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityKindName_0 = "CUPTI_ACTIVITY_KIND_INVALIDCUPTI_ACTIVITY_KIND_MEMCPYCUPTI_ACTIVITY_KIND_MEMSETCUPTI_ACTIVITY_KIND_KERNELCUPTI_ACTIVITY_KIND_DRIVERCUPTI_ACTIVITY_KIND_RUNTIMECUPTI_ACTIVITY_KIND_EVENTCUPTI_ACTIVITY_KIND_METRICCUPTI_ACTIVITY_KIND_DEVICECUPTI_ACTIVITY_KIND_CONTEXTCUPTI_ACTIVITY_KIND_CONCURRENT_KERNELCUPTI_ACTIVITY_KIND_NAMECUPTI_ACTIVITY_KIND_MARKERCUPTI_ACTIVITY_KIND_MARKER_DATACUPTI_ACTIVITY_KIND_SOURCE_LOCATORCUPTI_ACTIVITY_KIND_GLOBAL_ACCESSCUPTI_ACTIVITY_KIND_BRANCHCUPTI_ACTIVITY_KIND_OVERHEADCUPTI_ACTIVITY_KIND_CDP_KERNELCUPTI_ACTIVITY_KIND_PREEMPTIONCUPTI_ACTIVITY_KIND_ENVIRONMENTCUPTI_ACTIVITY_KIND_EVENT_INSTANCECUPTI_ACTIVITY_KIND_MEMCPY2CUPTI_ACTIVITY_KIND_METRIC_INSTANCECUPTI_ACTIVITY_KIND_INSTRUCTION_EXECUTIONCUPTI_ACTIVITY_KIND_UNIFIED_MEMORY_COUNTERCUPTI_ACTIVITY_KIND_FUNCTIONCUPTI_ACTIVITY_KIND_MODULECUPTI_ACTIVITY_KIND_DEVICE_ATTRIBUTECUPTI_ACTIVITY_KIND_SHARED_ACCESSCUPTI_ACTIVITY_KIND_PC_SAMPLINGCUPTI_ACTIVITY_KIND_PC_SAMPLING_RECORD_INFOCUPTI_ACTIVITY_KIND_INSTRUCTION_CORRELATIONCUPTI_ACTIVITY_KIND_OPENACC_DATACUPTI_ACTIVITY_KIND_OPENACC_LAUNCHCUPTI_ACTIVITY_KIND_OPENACC_OTHERCUPTI_ACTIVITY_KIND_CUDA_EVENTCUPTI_ACTIVITY_KIND_STREAMCUPTI_ACTIVITY_KIND_SYNCHRONIZATIONCUPTI_ACTIVITY_KIND_EXTERNAL_CORRELATIONCUPTI_ACTIVITY_KIND_NVLINKCUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENTCUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT_INSTANCECUPTI_ACTIVITY_KIND_INSTANTANEOUS_METRICCUPTI_ACTIVITY_KIND_INSTANTANEOUS_METRIC_INSTANCECUPTI_ACTIVITY_KIND_MEMORY"
	_CUpti_ActivityKindName_1 = "CUPTI_ACTIVITY_KIND_FORCE_INT"
)

var (
	_CUpti_ActivityKindIndex_0 = [...]uint16{0, 27, 53, 79, 105, 131, 158, 183, 209, 235, 262, 299, 323, 349, 380, 414, 447, 473, 501, 531, 561, 592, 626, 653, 688, 729, 771, 799, 825, 861, 894, 925, 968, 1011, 1043, 1077, 1110, 1140, 1166, 1201, 1241, 1267, 1306, 1354, 1394, 1443, 1469}
	_CUpti_ActivityKindIndex_1 = [...]uint8{0, 29}
)

func (i CUpti_ActivityKind) String() string {
	switch {
	case 0 <= i && i <= 45:
		return _CUpti_ActivityKindName_0[_CUpti_ActivityKindIndex_0[i]:_CUpti_ActivityKindIndex_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityKindName_1
	default:
		return fmt.Sprintf("CUpti_ActivityKind(%d)", i)
	}
}

var _CUpti_ActivityKindValues = []CUpti_ActivityKind{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 2147483647}

var _CUpti_ActivityKindNameToValueMap = map[string]CUpti_ActivityKind{
	_CUpti_ActivityKindName_0[0:27]:      0,
	_CUpti_ActivityKindName_0[27:53]:     1,
	_CUpti_ActivityKindName_0[53:79]:     2,
	_CUpti_ActivityKindName_0[79:105]:    3,
	_CUpti_ActivityKindName_0[105:131]:   4,
	_CUpti_ActivityKindName_0[131:158]:   5,
	_CUpti_ActivityKindName_0[158:183]:   6,
	_CUpti_ActivityKindName_0[183:209]:   7,
	_CUpti_ActivityKindName_0[209:235]:   8,
	_CUpti_ActivityKindName_0[235:262]:   9,
	_CUpti_ActivityKindName_0[262:299]:   10,
	_CUpti_ActivityKindName_0[299:323]:   11,
	_CUpti_ActivityKindName_0[323:349]:   12,
	_CUpti_ActivityKindName_0[349:380]:   13,
	_CUpti_ActivityKindName_0[380:414]:   14,
	_CUpti_ActivityKindName_0[414:447]:   15,
	_CUpti_ActivityKindName_0[447:473]:   16,
	_CUpti_ActivityKindName_0[473:501]:   17,
	_CUpti_ActivityKindName_0[501:531]:   18,
	_CUpti_ActivityKindName_0[531:561]:   19,
	_CUpti_ActivityKindName_0[561:592]:   20,
	_CUpti_ActivityKindName_0[592:626]:   21,
	_CUpti_ActivityKindName_0[626:653]:   22,
	_CUpti_ActivityKindName_0[653:688]:   23,
	_CUpti_ActivityKindName_0[688:729]:   24,
	_CUpti_ActivityKindName_0[729:771]:   25,
	_CUpti_ActivityKindName_0[771:799]:   26,
	_CUpti_ActivityKindName_0[799:825]:   27,
	_CUpti_ActivityKindName_0[825:861]:   28,
	_CUpti_ActivityKindName_0[861:894]:   29,
	_CUpti_ActivityKindName_0[894:925]:   30,
	_CUpti_ActivityKindName_0[925:968]:   31,
	_CUpti_ActivityKindName_0[968:1011]:  32,
	_CUpti_ActivityKindName_0[1011:1043]: 33,
	_CUpti_ActivityKindName_0[1043:1077]: 34,
	_CUpti_ActivityKindName_0[1077:1110]: 35,
	_CUpti_ActivityKindName_0[1110:1140]: 36,
	_CUpti_ActivityKindName_0[1140:1166]: 37,
	_CUpti_ActivityKindName_0[1166:1201]: 38,
	_CUpti_ActivityKindName_0[1201:1241]: 39,
	_CUpti_ActivityKindName_0[1241:1267]: 40,
	_CUpti_ActivityKindName_0[1267:1306]: 41,
	_CUpti_ActivityKindName_0[1306:1354]: 42,
	_CUpti_ActivityKindName_0[1354:1394]: 43,
	_CUpti_ActivityKindName_0[1394:1443]: 44,
	_CUpti_ActivityKindName_0[1443:1469]: 45,
	_CUpti_ActivityKindName_1[0:29]:      2147483647,
}

// CUpti_ActivityKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_ActivityKindString(s string) (CUpti_ActivityKind, error) {
	if val, ok := _CUpti_ActivityKindNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityKind values", s)
}

// CUpti_ActivityKindValues returns all values of the enum
func CUpti_ActivityKindValues() []CUpti_ActivityKind {
	return _CUpti_ActivityKindValues
}

// IsACUpti_ActivityKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_ActivityKind) IsACUpti_ActivityKind() bool {
	for _, v := range _CUpti_ActivityKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_ActivityKind
func (i CUpti_ActivityKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_ActivityKind
func (i *CUpti_ActivityKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityKind should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_ActivityKind
func (i CUpti_ActivityKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_ActivityKind
func (i *CUpti_ActivityKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_ActivityKindString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_ActivityKind
func (i CUpti_ActivityKind) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_ActivityKind
func (i *CUpti_ActivityKind) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_ActivityKindString(s)
	return err
}

func (i CUpti_ActivityKind) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_ActivityKind) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_ActivityKindString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
