// Code generated by "enumer -type=CUpti_ActivityUnifiedMemoryMigrationCause -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const _CUpti_ActivityUnifiedMemoryMigrationCauseName = "CUPTI_ACTIVITY_UNIFIED_MEMORY_MIGRATION_CAUSE_UNKNOWNCUPTI_ACTIVITY_UNIFIED_MEMORY_MIGRATION_CAUSE_USERCUPTI_ACTIVITY_UNIFIED_MEMORY_MIGRATION_CAUSE_COHERENCECUPTI_ACTIVITY_UNIFIED_MEMORY_MIGRATION_CAUSE_PREFETCHCUPTI_ACTIVITY_UNIFIED_MEMORY_MIGRATION_CAUSE_EVICTION"

var _CUpti_ActivityUnifiedMemoryMigrationCauseIndex = [...]uint16{0, 53, 103, 158, 212, 266}

func (i CUpti_ActivityUnifiedMemoryMigrationCause) String() string {
	if i < 0 || i >= CUpti_ActivityUnifiedMemoryMigrationCause(len(_CUpti_ActivityUnifiedMemoryMigrationCauseIndex)-1) {
		return fmt.Sprintf("CUpti_ActivityUnifiedMemoryMigrationCause(%d)", i)
	}
	return _CUpti_ActivityUnifiedMemoryMigrationCauseName[_CUpti_ActivityUnifiedMemoryMigrationCauseIndex[i]:_CUpti_ActivityUnifiedMemoryMigrationCauseIndex[i+1]]
}

var _CUpti_ActivityUnifiedMemoryMigrationCauseValues = []CUpti_ActivityUnifiedMemoryMigrationCause{0, 1, 2, 3, 4}

var _CUpti_ActivityUnifiedMemoryMigrationCauseNameToValueMap = map[string]CUpti_ActivityUnifiedMemoryMigrationCause{
	_CUpti_ActivityUnifiedMemoryMigrationCauseName[0:53]:    0,
	_CUpti_ActivityUnifiedMemoryMigrationCauseName[53:103]:  1,
	_CUpti_ActivityUnifiedMemoryMigrationCauseName[103:158]: 2,
	_CUpti_ActivityUnifiedMemoryMigrationCauseName[158:212]: 3,
	_CUpti_ActivityUnifiedMemoryMigrationCauseName[212:266]: 4,
}

// CUpti_ActivityUnifiedMemoryMigrationCauseString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_ActivityUnifiedMemoryMigrationCauseString(s string) (CUpti_ActivityUnifiedMemoryMigrationCause, error) {
	if val, ok := _CUpti_ActivityUnifiedMemoryMigrationCauseNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityUnifiedMemoryMigrationCause values", s)
}

// CUpti_ActivityUnifiedMemoryMigrationCauseValues returns all values of the enum
func CUpti_ActivityUnifiedMemoryMigrationCauseValues() []CUpti_ActivityUnifiedMemoryMigrationCause {
	return _CUpti_ActivityUnifiedMemoryMigrationCauseValues
}

// IsACUpti_ActivityUnifiedMemoryMigrationCause returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_ActivityUnifiedMemoryMigrationCause) IsACUpti_ActivityUnifiedMemoryMigrationCause() bool {
	for _, v := range _CUpti_ActivityUnifiedMemoryMigrationCauseValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_ActivityUnifiedMemoryMigrationCause
func (i CUpti_ActivityUnifiedMemoryMigrationCause) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_ActivityUnifiedMemoryMigrationCause
func (i *CUpti_ActivityUnifiedMemoryMigrationCause) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityUnifiedMemoryMigrationCause should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityUnifiedMemoryMigrationCauseString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_ActivityUnifiedMemoryMigrationCause
func (i CUpti_ActivityUnifiedMemoryMigrationCause) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_ActivityUnifiedMemoryMigrationCause
func (i *CUpti_ActivityUnifiedMemoryMigrationCause) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_ActivityUnifiedMemoryMigrationCauseString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_ActivityUnifiedMemoryMigrationCause
func (i CUpti_ActivityUnifiedMemoryMigrationCause) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_ActivityUnifiedMemoryMigrationCause
func (i *CUpti_ActivityUnifiedMemoryMigrationCause) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_ActivityUnifiedMemoryMigrationCauseString(s)
	return err
}

func (i CUpti_ActivityUnifiedMemoryMigrationCause) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_ActivityUnifiedMemoryMigrationCause) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_ActivityUnifiedMemoryMigrationCauseString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
