// Code generated by "enumer -type=CUpti_ActivityStreamFlag -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityStreamFlag_name_0 = "CUPTI_ACTIVITY_STREAM_CREATE_FLAG_UNKNOWNCUPTI_ACTIVITY_STREAM_CREATE_FLAG_DEFAULTCUPTI_ACTIVITY_STREAM_CREATE_FLAG_NON_BLOCKINGCUPTI_ACTIVITY_STREAM_CREATE_FLAG_NULL"
	_CUpti_ActivityStreamFlag_name_1 = "CUPTI_ACTIVITY_STREAM_CREATE_MASK"
	_CUpti_ActivityStreamFlag_name_2 = "CUPTI_ACTIVITY_STREAM_CREATE_FLAG_FORCE_INT"
)

var (
	_CUpti_ActivityStreamFlag_index_0 = [...]uint8{0, 41, 82, 128, 166}
	_CUpti_ActivityStreamFlag_index_1 = [...]uint8{0, 33}
	_CUpti_ActivityStreamFlag_index_2 = [...]uint8{0, 43}
)

func (i CUpti_ActivityStreamFlag) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _CUpti_ActivityStreamFlag_name_0[_CUpti_ActivityStreamFlag_index_0[i]:_CUpti_ActivityStreamFlag_index_0[i+1]]
	case i == 65535:
		return _CUpti_ActivityStreamFlag_name_1
	case i == 2147483647:
		return _CUpti_ActivityStreamFlag_name_2
	default:
		return fmt.Sprintf("CUpti_ActivityStreamFlag(%d)", i)
	}
}

var _CUpti_ActivityStreamFlagNameToValue_map = map[string]CUpti_ActivityStreamFlag{
	_CUpti_ActivityStreamFlag_name_0[0:41]:    0,
	_CUpti_ActivityStreamFlag_name_0[41:82]:   1,
	_CUpti_ActivityStreamFlag_name_0[82:128]:  2,
	_CUpti_ActivityStreamFlag_name_0[128:166]: 3,
	_CUpti_ActivityStreamFlag_name_1[0:33]:    65535,
	_CUpti_ActivityStreamFlag_name_2[0:43]:    2147483647,
}

func CUpti_ActivityStreamFlagString(s string) (CUpti_ActivityStreamFlag, error) {
	if val, ok := _CUpti_ActivityStreamFlagNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityStreamFlag values", s)
}

func (i CUpti_ActivityStreamFlag) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ActivityStreamFlag) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityStreamFlag should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityStreamFlagString(s)
	return err
}
