// Code generated by "enumer -type=CUpti_CallbackDomain -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_CallbackDomainName_0 = "CUPTI_CB_DOMAIN_INVALIDCUPTI_CB_DOMAIN_DRIVER_APICUPTI_CB_DOMAIN_RUNTIME_APICUPTI_CB_DOMAIN_RESOURCECUPTI_CB_DOMAIN_SYNCHRONIZECUPTI_CB_DOMAIN_NVTXCUPTI_CB_DOMAIN_SIZE"
	_CUpti_CallbackDomainName_1 = "CUPTI_CB_DOMAIN_FORCE_INT"
)

var (
	_CUpti_CallbackDomainIndex_0 = [...]uint8{0, 23, 49, 76, 100, 127, 147, 167}
	_CUpti_CallbackDomainIndex_1 = [...]uint8{0, 25}
)

func (i CUpti_CallbackDomain) String() string {
	switch {
	case 0 <= i && i <= 6:
		return _CUpti_CallbackDomainName_0[_CUpti_CallbackDomainIndex_0[i]:_CUpti_CallbackDomainIndex_0[i+1]]
	case i == 2147483647:
		return _CUpti_CallbackDomainName_1
	default:
		return fmt.Sprintf("CUpti_CallbackDomain(%d)", i)
	}
}

var _CUpti_CallbackDomainValues = []CUpti_CallbackDomain{0, 1, 2, 3, 4, 5, 6, 2147483647}

var _CUpti_CallbackDomainNameToValueMap = map[string]CUpti_CallbackDomain{
	_CUpti_CallbackDomainName_0[0:23]:    0,
	_CUpti_CallbackDomainName_0[23:49]:   1,
	_CUpti_CallbackDomainName_0[49:76]:   2,
	_CUpti_CallbackDomainName_0[76:100]:  3,
	_CUpti_CallbackDomainName_0[100:127]: 4,
	_CUpti_CallbackDomainName_0[127:147]: 5,
	_CUpti_CallbackDomainName_0[147:167]: 6,
	_CUpti_CallbackDomainName_1[0:25]:    2147483647,
}

// CUpti_CallbackDomainString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_CallbackDomainString(s string) (CUpti_CallbackDomain, error) {
	if val, ok := _CUpti_CallbackDomainNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_CallbackDomain values", s)
}

// CUpti_CallbackDomainValues returns all values of the enum
func CUpti_CallbackDomainValues() []CUpti_CallbackDomain {
	return _CUpti_CallbackDomainValues
}

// IsACUpti_CallbackDomain returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_CallbackDomain) IsACUpti_CallbackDomain() bool {
	for _, v := range _CUpti_CallbackDomainValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_CallbackDomain
func (i CUpti_CallbackDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_CallbackDomain
func (i *CUpti_CallbackDomain) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_CallbackDomain should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_CallbackDomainString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_CallbackDomain
func (i CUpti_CallbackDomain) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_CallbackDomain
func (i *CUpti_CallbackDomain) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_CallbackDomainString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_CallbackDomain
func (i CUpti_CallbackDomain) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_CallbackDomain
func (i *CUpti_CallbackDomain) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_CallbackDomainString(s)
	return err
}

func (i CUpti_CallbackDomain) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_CallbackDomain) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_CallbackDomainString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
