// Code generated by "enumer -type=CUpti_ActivityThreadIdType -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityThreadIdTypeName_0 = "CUPTI_ACTIVITY_THREAD_ID_TYPE_DEFAULTCUPTI_ACTIVITY_THREAD_ID_TYPE_SYSTEM"
	_CUpti_ActivityThreadIdTypeName_1 = "CUPTI_ACTIVITY_THREAD_ID_TYPE_FORCE_INT"
)

var (
	_CUpti_ActivityThreadIdTypeIndex_0 = [...]uint8{0, 37, 73}
	_CUpti_ActivityThreadIdTypeIndex_1 = [...]uint8{0, 39}
)

func (i CUpti_ActivityThreadIdType) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _CUpti_ActivityThreadIdTypeName_0[_CUpti_ActivityThreadIdTypeIndex_0[i]:_CUpti_ActivityThreadIdTypeIndex_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityThreadIdTypeName_1
	default:
		return fmt.Sprintf("CUpti_ActivityThreadIdType(%d)", i)
	}
}

var _CUpti_ActivityThreadIdTypeValues = []CUpti_ActivityThreadIdType{0, 1, 2147483647}

var _CUpti_ActivityThreadIdTypeNameToValueMap = map[string]CUpti_ActivityThreadIdType{
	_CUpti_ActivityThreadIdTypeName_0[0:37]:  0,
	_CUpti_ActivityThreadIdTypeName_0[37:73]: 1,
	_CUpti_ActivityThreadIdTypeName_1[0:39]:  2147483647,
}

// CUpti_ActivityThreadIdTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_ActivityThreadIdTypeString(s string) (CUpti_ActivityThreadIdType, error) {
	if val, ok := _CUpti_ActivityThreadIdTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityThreadIdType values", s)
}

// CUpti_ActivityThreadIdTypeValues returns all values of the enum
func CUpti_ActivityThreadIdTypeValues() []CUpti_ActivityThreadIdType {
	return _CUpti_ActivityThreadIdTypeValues
}

// IsACUpti_ActivityThreadIdType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_ActivityThreadIdType) IsACUpti_ActivityThreadIdType() bool {
	for _, v := range _CUpti_ActivityThreadIdTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_ActivityThreadIdType
func (i CUpti_ActivityThreadIdType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_ActivityThreadIdType
func (i *CUpti_ActivityThreadIdType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityThreadIdType should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityThreadIdTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_ActivityThreadIdType
func (i CUpti_ActivityThreadIdType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_ActivityThreadIdType
func (i *CUpti_ActivityThreadIdType) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_ActivityThreadIdTypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_ActivityThreadIdType
func (i CUpti_ActivityThreadIdType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_ActivityThreadIdType
func (i *CUpti_ActivityThreadIdType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_ActivityThreadIdTypeString(s)
	return err
}

func (i CUpti_ActivityThreadIdType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_ActivityThreadIdType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_ActivityThreadIdTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
