// Code generated by "enumer -type=CUpti_MetricValueKind -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_MetricValueKindName_0 = "CUPTI_METRIC_VALUE_KIND_DOUBLECUPTI_METRIC_VALUE_KIND_UINT64CUPTI_METRIC_VALUE_KIND_PERCENTCUPTI_METRIC_VALUE_KIND_THROUGHPUTCUPTI_METRIC_VALUE_KIND_INT64CUPTI_METRIC_VALUE_KIND_UTILIZATION_LEVEL"
	_CUpti_MetricValueKindName_1 = "CUPTI_METRIC_VALUE_KIND_FORCE_INT"
)

var (
	_CUpti_MetricValueKindIndex_0 = [...]uint8{0, 30, 60, 91, 125, 154, 195}
	_CUpti_MetricValueKindIndex_1 = [...]uint8{0, 33}
)

func (i CUpti_MetricValueKind) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _CUpti_MetricValueKindName_0[_CUpti_MetricValueKindIndex_0[i]:_CUpti_MetricValueKindIndex_0[i+1]]
	case i == 2147483647:
		return _CUpti_MetricValueKindName_1
	default:
		return fmt.Sprintf("CUpti_MetricValueKind(%d)", i)
	}
}

var _CUpti_MetricValueKindValues = []CUpti_MetricValueKind{0, 1, 2, 3, 4, 5, 2147483647}

var _CUpti_MetricValueKindNameToValueMap = map[string]CUpti_MetricValueKind{
	_CUpti_MetricValueKindName_0[0:30]:    0,
	_CUpti_MetricValueKindName_0[30:60]:   1,
	_CUpti_MetricValueKindName_0[60:91]:   2,
	_CUpti_MetricValueKindName_0[91:125]:  3,
	_CUpti_MetricValueKindName_0[125:154]: 4,
	_CUpti_MetricValueKindName_0[154:195]: 5,
	_CUpti_MetricValueKindName_1[0:33]:    2147483647,
}

// CUpti_MetricValueKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_MetricValueKindString(s string) (CUpti_MetricValueKind, error) {
	if val, ok := _CUpti_MetricValueKindNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_MetricValueKind values", s)
}

// CUpti_MetricValueKindValues returns all values of the enum
func CUpti_MetricValueKindValues() []CUpti_MetricValueKind {
	return _CUpti_MetricValueKindValues
}

// IsACUpti_MetricValueKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_MetricValueKind) IsACUpti_MetricValueKind() bool {
	for _, v := range _CUpti_MetricValueKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_MetricValueKind
func (i CUpti_MetricValueKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_MetricValueKind
func (i *CUpti_MetricValueKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_MetricValueKind should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_MetricValueKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_MetricValueKind
func (i CUpti_MetricValueKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_MetricValueKind
func (i *CUpti_MetricValueKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_MetricValueKindString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_MetricValueKind
func (i CUpti_MetricValueKind) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_MetricValueKind
func (i *CUpti_MetricValueKind) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_MetricValueKindString(s)
	return err
}

func (i CUpti_MetricValueKind) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_MetricValueKind) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_MetricValueKindString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
