// Code generated by "enumer -type=CUpti_ReadEventFlags -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ReadEventFlagsName_0 = "CUPTI_EVENT_READ_FLAG_NONE"
	_CUpti_ReadEventFlagsName_1 = "CUPTI_EVENT_READ_FLAG_FORCE_INT"
)

var (
	_CUpti_ReadEventFlagsIndex_0 = [...]uint8{0, 26}
	_CUpti_ReadEventFlagsIndex_1 = [...]uint8{0, 31}
)

func (i CUpti_ReadEventFlags) String() string {
	switch {
	case i == 0:
		return _CUpti_ReadEventFlagsName_0
	case i == 2147483647:
		return _CUpti_ReadEventFlagsName_1
	default:
		return fmt.Sprintf("CUpti_ReadEventFlags(%d)", i)
	}
}

var _CUpti_ReadEventFlagsValues = []CUpti_ReadEventFlags{0, 2147483647}

var _CUpti_ReadEventFlagsNameToValueMap = map[string]CUpti_ReadEventFlags{
	_CUpti_ReadEventFlagsName_0[0:26]: 0,
	_CUpti_ReadEventFlagsName_1[0:31]: 2147483647,
}

// CUpti_ReadEventFlagsString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_ReadEventFlagsString(s string) (CUpti_ReadEventFlags, error) {
	if val, ok := _CUpti_ReadEventFlagsNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ReadEventFlags values", s)
}

// CUpti_ReadEventFlagsValues returns all values of the enum
func CUpti_ReadEventFlagsValues() []CUpti_ReadEventFlags {
	return _CUpti_ReadEventFlagsValues
}

// IsACUpti_ReadEventFlags returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_ReadEventFlags) IsACUpti_ReadEventFlags() bool {
	for _, v := range _CUpti_ReadEventFlagsValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_ReadEventFlags
func (i CUpti_ReadEventFlags) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_ReadEventFlags
func (i *CUpti_ReadEventFlags) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ReadEventFlags should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ReadEventFlagsString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_ReadEventFlags
func (i CUpti_ReadEventFlags) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_ReadEventFlags
func (i *CUpti_ReadEventFlags) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_ReadEventFlagsString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_ReadEventFlags
func (i CUpti_ReadEventFlags) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_ReadEventFlags
func (i *CUpti_ReadEventFlags) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_ReadEventFlagsString(s)
	return err
}

func (i CUpti_ReadEventFlags) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_ReadEventFlags) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_ReadEventFlagsString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
