// Code generated by "enumer -type=CUpti_ActivityPCSamplingStallReason -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityPCSamplingStallReason_name_0 = "CUPTI_ACTIVITY_PC_SAMPLING_STALL_INVALIDCUPTI_ACTIVITY_PC_SAMPLING_STALL_NONECUPTI_ACTIVITY_PC_SAMPLING_STALL_INST_FETCHCUPTI_ACTIVITY_PC_SAMPLING_STALL_EXEC_DEPENDENCYCUPTI_ACTIVITY_PC_SAMPLING_STALL_MEMORY_DEPENDENCYCUPTI_ACTIVITY_PC_SAMPLING_STALL_TEXTURECUPTI_ACTIVITY_PC_SAMPLING_STALL_SYNCCUPTI_ACTIVITY_PC_SAMPLING_STALL_CONSTANT_MEMORY_DEPENDENCYCUPTI_ACTIVITY_PC_SAMPLING_STALL_PIPE_BUSYCUPTI_ACTIVITY_PC_SAMPLING_STALL_MEMORY_THROTTLECUPTI_ACTIVITY_PC_SAMPLING_STALL_NOT_SELECTEDCUPTI_ACTIVITY_PC_SAMPLING_STALL_OTHERCUPTI_ACTIVITY_PC_SAMPLING_STALL_SLEEPING"
	_CUpti_ActivityPCSamplingStallReason_name_1 = "CUPTI_ACTIVITY_PC_SAMPLING_STALL_FORCE_INT"
)

var (
	_CUpti_ActivityPCSamplingStallReason_index_0 = [...]uint16{0, 40, 77, 120, 168, 218, 258, 295, 354, 396, 444, 489, 527, 568}
	_CUpti_ActivityPCSamplingStallReason_index_1 = [...]uint8{0, 42}
)

func (i CUpti_ActivityPCSamplingStallReason) String() string {
	switch {
	case 0 <= i && i <= 12:
		return _CUpti_ActivityPCSamplingStallReason_name_0[_CUpti_ActivityPCSamplingStallReason_index_0[i]:_CUpti_ActivityPCSamplingStallReason_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityPCSamplingStallReason_name_1
	default:
		return fmt.Sprintf("CUpti_ActivityPCSamplingStallReason(%d)", i)
	}
}

var _CUpti_ActivityPCSamplingStallReasonNameToValue_map = map[string]CUpti_ActivityPCSamplingStallReason{
	_CUpti_ActivityPCSamplingStallReason_name_0[0:40]:    0,
	_CUpti_ActivityPCSamplingStallReason_name_0[40:77]:   1,
	_CUpti_ActivityPCSamplingStallReason_name_0[77:120]:  2,
	_CUpti_ActivityPCSamplingStallReason_name_0[120:168]: 3,
	_CUpti_ActivityPCSamplingStallReason_name_0[168:218]: 4,
	_CUpti_ActivityPCSamplingStallReason_name_0[218:258]: 5,
	_CUpti_ActivityPCSamplingStallReason_name_0[258:295]: 6,
	_CUpti_ActivityPCSamplingStallReason_name_0[295:354]: 7,
	_CUpti_ActivityPCSamplingStallReason_name_0[354:396]: 8,
	_CUpti_ActivityPCSamplingStallReason_name_0[396:444]: 9,
	_CUpti_ActivityPCSamplingStallReason_name_0[444:489]: 10,
	_CUpti_ActivityPCSamplingStallReason_name_0[489:527]: 11,
	_CUpti_ActivityPCSamplingStallReason_name_0[527:568]: 12,
	_CUpti_ActivityPCSamplingStallReason_name_1[0:42]:    2147483647,
}

func CUpti_ActivityPCSamplingStallReasonString(s string) (CUpti_ActivityPCSamplingStallReason, error) {
	if val, ok := _CUpti_ActivityPCSamplingStallReasonNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityPCSamplingStallReason values", s)
}

func (i CUpti_ActivityPCSamplingStallReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ActivityPCSamplingStallReason) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityPCSamplingStallReason should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityPCSamplingStallReasonString(s)
	return err
}
