// Code generated by "enumer -type=CUpti_ActivityStreamFlag -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityStreamFlagName_0 = "CUPTI_ACTIVITY_STREAM_CREATE_FLAG_UNKNOWNCUPTI_ACTIVITY_STREAM_CREATE_FLAG_DEFAULTCUPTI_ACTIVITY_STREAM_CREATE_FLAG_NON_BLOCKINGCUPTI_ACTIVITY_STREAM_CREATE_FLAG_NULL"
	_CUpti_ActivityStreamFlagName_1 = "CUPTI_ACTIVITY_STREAM_CREATE_MASK"
	_CUpti_ActivityStreamFlagName_2 = "CUPTI_ACTIVITY_STREAM_CREATE_FLAG_FORCE_INT"
)

var (
	_CUpti_ActivityStreamFlagIndex_0 = [...]uint8{0, 41, 82, 128, 166}
	_CUpti_ActivityStreamFlagIndex_1 = [...]uint8{0, 33}
	_CUpti_ActivityStreamFlagIndex_2 = [...]uint8{0, 43}
)

func (i CUpti_ActivityStreamFlag) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _CUpti_ActivityStreamFlagName_0[_CUpti_ActivityStreamFlagIndex_0[i]:_CUpti_ActivityStreamFlagIndex_0[i+1]]
	case i == 65535:
		return _CUpti_ActivityStreamFlagName_1
	case i == 2147483647:
		return _CUpti_ActivityStreamFlagName_2
	default:
		return fmt.Sprintf("CUpti_ActivityStreamFlag(%d)", i)
	}
}

var _CUpti_ActivityStreamFlagValues = []CUpti_ActivityStreamFlag{0, 1, 2, 3, 65535, 2147483647}

var _CUpti_ActivityStreamFlagNameToValueMap = map[string]CUpti_ActivityStreamFlag{
	_CUpti_ActivityStreamFlagName_0[0:41]:    0,
	_CUpti_ActivityStreamFlagName_0[41:82]:   1,
	_CUpti_ActivityStreamFlagName_0[82:128]:  2,
	_CUpti_ActivityStreamFlagName_0[128:166]: 3,
	_CUpti_ActivityStreamFlagName_1[0:33]:    65535,
	_CUpti_ActivityStreamFlagName_2[0:43]:    2147483647,
}

// CUpti_ActivityStreamFlagString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_ActivityStreamFlagString(s string) (CUpti_ActivityStreamFlag, error) {
	if val, ok := _CUpti_ActivityStreamFlagNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityStreamFlag values", s)
}

// CUpti_ActivityStreamFlagValues returns all values of the enum
func CUpti_ActivityStreamFlagValues() []CUpti_ActivityStreamFlag {
	return _CUpti_ActivityStreamFlagValues
}

// IsACUpti_ActivityStreamFlag returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_ActivityStreamFlag) IsACUpti_ActivityStreamFlag() bool {
	for _, v := range _CUpti_ActivityStreamFlagValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_ActivityStreamFlag
func (i CUpti_ActivityStreamFlag) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_ActivityStreamFlag
func (i *CUpti_ActivityStreamFlag) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityStreamFlag should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityStreamFlagString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_ActivityStreamFlag
func (i CUpti_ActivityStreamFlag) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_ActivityStreamFlag
func (i *CUpti_ActivityStreamFlag) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_ActivityStreamFlagString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_ActivityStreamFlag
func (i CUpti_ActivityStreamFlag) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_ActivityStreamFlag
func (i *CUpti_ActivityStreamFlag) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_ActivityStreamFlagString(s)
	return err
}

func (i CUpti_ActivityStreamFlag) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_ActivityStreamFlag) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_ActivityStreamFlagString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
