// Code generated by "enumer -type=CUpti_EventAttribute -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_EventAttributeName_0 = "CUPTI_EVENT_ATTR_NAMECUPTI_EVENT_ATTR_SHORT_DESCRIPTIONCUPTI_EVENT_ATTR_LONG_DESCRIPTIONCUPTI_EVENT_ATTR_CATEGORY"
	_CUpti_EventAttributeName_1 = "CUPTI_EVENT_ATTR_FORCE_INT"
)

var (
	_CUpti_EventAttributeIndex_0 = [...]uint8{0, 21, 55, 88, 113}
	_CUpti_EventAttributeIndex_1 = [...]uint8{0, 26}
)

func (i CUpti_EventAttribute) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _CUpti_EventAttributeName_0[_CUpti_EventAttributeIndex_0[i]:_CUpti_EventAttributeIndex_0[i+1]]
	case i == 2147483647:
		return _CUpti_EventAttributeName_1
	default:
		return fmt.Sprintf("CUpti_EventAttribute(%d)", i)
	}
}

var _CUpti_EventAttributeValues = []CUpti_EventAttribute{0, 1, 2, 3, 2147483647}

var _CUpti_EventAttributeNameToValueMap = map[string]CUpti_EventAttribute{
	_CUpti_EventAttributeName_0[0:21]:   0,
	_CUpti_EventAttributeName_0[21:55]:  1,
	_CUpti_EventAttributeName_0[55:88]:  2,
	_CUpti_EventAttributeName_0[88:113]: 3,
	_CUpti_EventAttributeName_1[0:26]:   2147483647,
}

// CUpti_EventAttributeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_EventAttributeString(s string) (CUpti_EventAttribute, error) {
	if val, ok := _CUpti_EventAttributeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_EventAttribute values", s)
}

// CUpti_EventAttributeValues returns all values of the enum
func CUpti_EventAttributeValues() []CUpti_EventAttribute {
	return _CUpti_EventAttributeValues
}

// IsACUpti_EventAttribute returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_EventAttribute) IsACUpti_EventAttribute() bool {
	for _, v := range _CUpti_EventAttributeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_EventAttribute
func (i CUpti_EventAttribute) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_EventAttribute
func (i *CUpti_EventAttribute) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_EventAttribute should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_EventAttributeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_EventAttribute
func (i CUpti_EventAttribute) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_EventAttribute
func (i *CUpti_EventAttribute) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_EventAttributeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_EventAttribute
func (i CUpti_EventAttribute) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_EventAttribute
func (i *CUpti_EventAttribute) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_EventAttributeString(s)
	return err
}

func (i CUpti_EventAttribute) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_EventAttribute) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_EventAttributeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
