// Code generated by "enumer -type=CUpti_MetricEvaluationMode -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_MetricEvaluationModeName_0 = "CUPTI_METRIC_EVALUATION_MODE_PER_INSTANCECUPTI_METRIC_EVALUATION_MODE_AGGREGATE"
	_CUpti_MetricEvaluationModeName_1 = "CUPTI_METRIC_EVALUATION_MODE_FORCE_INT"
)

var (
	_CUpti_MetricEvaluationModeIndex_0 = [...]uint8{0, 41, 79}
	_CUpti_MetricEvaluationModeIndex_1 = [...]uint8{0, 38}
)

func (i CUpti_MetricEvaluationMode) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _CUpti_MetricEvaluationModeName_0[_CUpti_MetricEvaluationModeIndex_0[i]:_CUpti_MetricEvaluationModeIndex_0[i+1]]
	case i == 2147483647:
		return _CUpti_MetricEvaluationModeName_1
	default:
		return fmt.Sprintf("CUpti_MetricEvaluationMode(%d)", i)
	}
}

var _CUpti_MetricEvaluationModeValues = []CUpti_MetricEvaluationMode{1, 2, 2147483647}

var _CUpti_MetricEvaluationModeNameToValueMap = map[string]CUpti_MetricEvaluationMode{
	_CUpti_MetricEvaluationModeName_0[0:41]:  1,
	_CUpti_MetricEvaluationModeName_0[41:79]: 2,
	_CUpti_MetricEvaluationModeName_1[0:38]:  2147483647,
}

// CUpti_MetricEvaluationModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_MetricEvaluationModeString(s string) (CUpti_MetricEvaluationMode, error) {
	if val, ok := _CUpti_MetricEvaluationModeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_MetricEvaluationMode values", s)
}

// CUpti_MetricEvaluationModeValues returns all values of the enum
func CUpti_MetricEvaluationModeValues() []CUpti_MetricEvaluationMode {
	return _CUpti_MetricEvaluationModeValues
}

// IsACUpti_MetricEvaluationMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_MetricEvaluationMode) IsACUpti_MetricEvaluationMode() bool {
	for _, v := range _CUpti_MetricEvaluationModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_MetricEvaluationMode
func (i CUpti_MetricEvaluationMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_MetricEvaluationMode
func (i *CUpti_MetricEvaluationMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_MetricEvaluationMode should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_MetricEvaluationModeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_MetricEvaluationMode
func (i CUpti_MetricEvaluationMode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_MetricEvaluationMode
func (i *CUpti_MetricEvaluationMode) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_MetricEvaluationModeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_MetricEvaluationMode
func (i CUpti_MetricEvaluationMode) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_MetricEvaluationMode
func (i *CUpti_MetricEvaluationMode) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_MetricEvaluationModeString(s)
	return err
}

func (i CUpti_MetricEvaluationMode) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_MetricEvaluationMode) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_MetricEvaluationModeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
