// Code generated by "enumer -type=CUpti_ActivityUnifiedMemoryMigrationCause -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const _CUpti_ActivityUnifiedMemoryMigrationCause_name = "CUPTI_ACTIVITY_UNIFIED_MEMORY_MIGRATION_CAUSE_UNKNOWNCUPTI_ACTIVITY_UNIFIED_MEMORY_MIGRATION_CAUSE_USERCUPTI_ACTIVITY_UNIFIED_MEMORY_MIGRATION_CAUSE_COHERENCECUPTI_ACTIVITY_UNIFIED_MEMORY_MIGRATION_CAUSE_PREFETCHCUPTI_ACTIVITY_UNIFIED_MEMORY_MIGRATION_CAUSE_EVICTION"

var _CUpti_ActivityUnifiedMemoryMigrationCause_index = [...]uint16{0, 53, 103, 158, 212, 266}

func (i CUpti_ActivityUnifiedMemoryMigrationCause) String() string {
	if i < 0 || i >= CUpti_ActivityUnifiedMemoryMigrationCause(len(_CUpti_ActivityUnifiedMemoryMigrationCause_index)-1) {
		return fmt.Sprintf("CUpti_ActivityUnifiedMemoryMigrationCause(%d)", i)
	}
	return _CUpti_ActivityUnifiedMemoryMigrationCause_name[_CUpti_ActivityUnifiedMemoryMigrationCause_index[i]:_CUpti_ActivityUnifiedMemoryMigrationCause_index[i+1]]
}

var _CUpti_ActivityUnifiedMemoryMigrationCauseNameToValue_map = map[string]CUpti_ActivityUnifiedMemoryMigrationCause{
	_CUpti_ActivityUnifiedMemoryMigrationCause_name[0:53]:    0,
	_CUpti_ActivityUnifiedMemoryMigrationCause_name[53:103]:  1,
	_CUpti_ActivityUnifiedMemoryMigrationCause_name[103:158]: 2,
	_CUpti_ActivityUnifiedMemoryMigrationCause_name[158:212]: 3,
	_CUpti_ActivityUnifiedMemoryMigrationCause_name[212:266]: 4,
}

func CUpti_ActivityUnifiedMemoryMigrationCauseString(s string) (CUpti_ActivityUnifiedMemoryMigrationCause, error) {
	if val, ok := _CUpti_ActivityUnifiedMemoryMigrationCauseNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityUnifiedMemoryMigrationCause values", s)
}

func (i CUpti_ActivityUnifiedMemoryMigrationCause) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ActivityUnifiedMemoryMigrationCause) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityUnifiedMemoryMigrationCause should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityUnifiedMemoryMigrationCauseString(s)
	return err
}
