// Code generated by "enumer -type=CUpti_ActivityPartitionedGlobalCacheConfig -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityPartitionedGlobalCacheConfigName_0 = "CUPTI_ACTIVITY_PARTITIONED_GLOBAL_CACHE_CONFIG_UNKNOWNCUPTI_ACTIVITY_PARTITIONED_GLOBAL_CACHE_CONFIG_NOT_SUPPORTEDCUPTI_ACTIVITY_PARTITIONED_GLOBAL_CACHE_CONFIG_OFFCUPTI_ACTIVITY_PARTITIONED_GLOBAL_CACHE_CONFIG_ON"
	_CUpti_ActivityPartitionedGlobalCacheConfigName_1 = "CUPTI_ACTIVITY_PARTITIONED_GLOBAL_CACHE_CONFIG_FORCE_INT"
)

var (
	_CUpti_ActivityPartitionedGlobalCacheConfigIndex_0 = [...]uint8{0, 54, 114, 164, 213}
	_CUpti_ActivityPartitionedGlobalCacheConfigIndex_1 = [...]uint8{0, 56}
)

func (i CUpti_ActivityPartitionedGlobalCacheConfig) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _CUpti_ActivityPartitionedGlobalCacheConfigName_0[_CUpti_ActivityPartitionedGlobalCacheConfigIndex_0[i]:_CUpti_ActivityPartitionedGlobalCacheConfigIndex_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityPartitionedGlobalCacheConfigName_1
	default:
		return fmt.Sprintf("CUpti_ActivityPartitionedGlobalCacheConfig(%d)", i)
	}
}

var _CUpti_ActivityPartitionedGlobalCacheConfigValues = []CUpti_ActivityPartitionedGlobalCacheConfig{0, 1, 2, 3, 2147483647}

var _CUpti_ActivityPartitionedGlobalCacheConfigNameToValueMap = map[string]CUpti_ActivityPartitionedGlobalCacheConfig{
	_CUpti_ActivityPartitionedGlobalCacheConfigName_0[0:54]:    0,
	_CUpti_ActivityPartitionedGlobalCacheConfigName_0[54:114]:  1,
	_CUpti_ActivityPartitionedGlobalCacheConfigName_0[114:164]: 2,
	_CUpti_ActivityPartitionedGlobalCacheConfigName_0[164:213]: 3,
	_CUpti_ActivityPartitionedGlobalCacheConfigName_1[0:56]:    2147483647,
}

// CUpti_ActivityPartitionedGlobalCacheConfigString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_ActivityPartitionedGlobalCacheConfigString(s string) (CUpti_ActivityPartitionedGlobalCacheConfig, error) {
	if val, ok := _CUpti_ActivityPartitionedGlobalCacheConfigNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityPartitionedGlobalCacheConfig values", s)
}

// CUpti_ActivityPartitionedGlobalCacheConfigValues returns all values of the enum
func CUpti_ActivityPartitionedGlobalCacheConfigValues() []CUpti_ActivityPartitionedGlobalCacheConfig {
	return _CUpti_ActivityPartitionedGlobalCacheConfigValues
}

// IsACUpti_ActivityPartitionedGlobalCacheConfig returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_ActivityPartitionedGlobalCacheConfig) IsACUpti_ActivityPartitionedGlobalCacheConfig() bool {
	for _, v := range _CUpti_ActivityPartitionedGlobalCacheConfigValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_ActivityPartitionedGlobalCacheConfig
func (i CUpti_ActivityPartitionedGlobalCacheConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_ActivityPartitionedGlobalCacheConfig
func (i *CUpti_ActivityPartitionedGlobalCacheConfig) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityPartitionedGlobalCacheConfig should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityPartitionedGlobalCacheConfigString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_ActivityPartitionedGlobalCacheConfig
func (i CUpti_ActivityPartitionedGlobalCacheConfig) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_ActivityPartitionedGlobalCacheConfig
func (i *CUpti_ActivityPartitionedGlobalCacheConfig) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_ActivityPartitionedGlobalCacheConfigString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_ActivityPartitionedGlobalCacheConfig
func (i CUpti_ActivityPartitionedGlobalCacheConfig) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_ActivityPartitionedGlobalCacheConfig
func (i *CUpti_ActivityPartitionedGlobalCacheConfig) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_ActivityPartitionedGlobalCacheConfigString(s)
	return err
}

func (i CUpti_ActivityPartitionedGlobalCacheConfig) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_ActivityPartitionedGlobalCacheConfig) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_ActivityPartitionedGlobalCacheConfigString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
