// Code generated by "enumer -type=CUpti_ActivityMemoryKind -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityMemoryKind_name_0 = "CUPTI_ACTIVITY_MEMORY_KIND_UNKNOWNCUPTI_ACTIVITY_MEMORY_KIND_PAGEABLECUPTI_ACTIVITY_MEMORY_KIND_PINNEDCUPTI_ACTIVITY_MEMORY_KIND_DEVICECUPTI_ACTIVITY_MEMORY_KIND_ARRAYCUPTI_ACTIVITY_MEMORY_KIND_MANAGEDCUPTI_ACTIVITY_MEMORY_KIND_DEVICE_STATICCUPTI_ACTIVITY_MEMORY_KIND_MANAGED_STATIC"
	_CUpti_ActivityMemoryKind_name_1 = "CUPTI_ACTIVITY_MEMORY_KIND_FORCE_INT"
)

var (
	_CUpti_ActivityMemoryKind_index_0 = [...]uint16{0, 34, 69, 102, 135, 167, 201, 241, 282}
	_CUpti_ActivityMemoryKind_index_1 = [...]uint8{0, 36}
)

func (i CUpti_ActivityMemoryKind) String() string {
	switch {
	case 0 <= i && i <= 7:
		return _CUpti_ActivityMemoryKind_name_0[_CUpti_ActivityMemoryKind_index_0[i]:_CUpti_ActivityMemoryKind_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityMemoryKind_name_1
	default:
		return fmt.Sprintf("CUpti_ActivityMemoryKind(%d)", i)
	}
}

var _CUpti_ActivityMemoryKindNameToValue_map = map[string]CUpti_ActivityMemoryKind{
	_CUpti_ActivityMemoryKind_name_0[0:34]:    0,
	_CUpti_ActivityMemoryKind_name_0[34:69]:   1,
	_CUpti_ActivityMemoryKind_name_0[69:102]:  2,
	_CUpti_ActivityMemoryKind_name_0[102:135]: 3,
	_CUpti_ActivityMemoryKind_name_0[135:167]: 4,
	_CUpti_ActivityMemoryKind_name_0[167:201]: 5,
	_CUpti_ActivityMemoryKind_name_0[201:241]: 6,
	_CUpti_ActivityMemoryKind_name_0[241:282]: 7,
	_CUpti_ActivityMemoryKind_name_1[0:36]:    2147483647,
}

func CUpti_ActivityMemoryKindString(s string) (CUpti_ActivityMemoryKind, error) {
	if val, ok := _CUpti_ActivityMemoryKindNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityMemoryKind values", s)
}

func (i CUpti_ActivityMemoryKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ActivityMemoryKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityMemoryKind should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityMemoryKindString(s)
	return err
}
