// Code generated by "enumer -type=CUpti_MetricEvaluationMode -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_MetricEvaluationMode_name_0 = "CUPTI_METRIC_EVALUATION_MODE_PER_INSTANCECUPTI_METRIC_EVALUATION_MODE_AGGREGATE"
	_CUpti_MetricEvaluationMode_name_1 = "CUPTI_METRIC_EVALUATION_MODE_FORCE_INT"
)

var (
	_CUpti_MetricEvaluationMode_index_0 = [...]uint8{0, 41, 79}
	_CUpti_MetricEvaluationMode_index_1 = [...]uint8{0, 38}
)

func (i CUpti_MetricEvaluationMode) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _CUpti_MetricEvaluationMode_name_0[_CUpti_MetricEvaluationMode_index_0[i]:_CUpti_MetricEvaluationMode_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_MetricEvaluationMode_name_1
	default:
		return fmt.Sprintf("CUpti_MetricEvaluationMode(%d)", i)
	}
}

var _CUpti_MetricEvaluationModeNameToValue_map = map[string]CUpti_MetricEvaluationMode{
	_CUpti_MetricEvaluationMode_name_0[0:41]:  1,
	_CUpti_MetricEvaluationMode_name_0[41:79]: 2,
	_CUpti_MetricEvaluationMode_name_1[0:38]:  2147483647,
}

func CUpti_MetricEvaluationModeString(s string) (CUpti_MetricEvaluationMode, error) {
	if val, ok := _CUpti_MetricEvaluationModeNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_MetricEvaluationMode values", s)
}

func (i CUpti_MetricEvaluationMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_MetricEvaluationMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_MetricEvaluationMode should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_MetricEvaluationModeString(s)
	return err
}
