// Code generated by "enumer -type=CUpti_ActivitySynchronizationType -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivitySynchronizationType_name_0 = "CUPTI_ACTIVITY_SYNCHRONIZATION_TYPE_UNKNOWNCUPTI_ACTIVITY_SYNCHRONIZATION_TYPE_EVENT_SYNCHRONIZECUPTI_ACTIVITY_SYNCHRONIZATION_TYPE_STREAM_WAIT_EVENTCUPTI_ACTIVITY_SYNCHRONIZATION_TYPE_STREAM_SYNCHRONIZECUPTI_ACTIVITY_SYNCHRONIZATION_TYPE_CONTEXT_SYNCHRONIZE"
	_CUpti_ActivitySynchronizationType_name_1 = "CUPTI_ACTIVITY_SYNCHRONIZATION_TYPE_FORCE_INT"
)

var (
	_CUpti_ActivitySynchronizationType_index_0 = [...]uint16{0, 43, 96, 149, 203, 258}
	_CUpti_ActivitySynchronizationType_index_1 = [...]uint8{0, 45}
)

func (i CUpti_ActivitySynchronizationType) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _CUpti_ActivitySynchronizationType_name_0[_CUpti_ActivitySynchronizationType_index_0[i]:_CUpti_ActivitySynchronizationType_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivitySynchronizationType_name_1
	default:
		return fmt.Sprintf("CUpti_ActivitySynchronizationType(%d)", i)
	}
}

var _CUpti_ActivitySynchronizationTypeNameToValue_map = map[string]CUpti_ActivitySynchronizationType{
	_CUpti_ActivitySynchronizationType_name_0[0:43]:    0,
	_CUpti_ActivitySynchronizationType_name_0[43:96]:   1,
	_CUpti_ActivitySynchronizationType_name_0[96:149]:  2,
	_CUpti_ActivitySynchronizationType_name_0[149:203]: 3,
	_CUpti_ActivitySynchronizationType_name_0[203:258]: 4,
	_CUpti_ActivitySynchronizationType_name_1[0:45]:    2147483647,
}

func CUpti_ActivitySynchronizationTypeString(s string) (CUpti_ActivitySynchronizationType, error) {
	if val, ok := _CUpti_ActivitySynchronizationTypeNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivitySynchronizationType values", s)
}

func (i CUpti_ActivitySynchronizationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_ActivitySynchronizationType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivitySynchronizationType should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivitySynchronizationTypeString(s)
	return err
}
