// Code generated by "enumer -type=CUpti_MetricCategory -json"; DO NOT EDIT

package types

import (
	"encoding/json"
	"fmt"
)

const (
	_CUpti_MetricCategory_name_0 = "CUPTI_METRIC_CATEGORY_MEMORYCUPTI_METRIC_CATEGORY_INSTRUCTIONCUPTI_METRIC_CATEGORY_MULTIPROCESSORCUPTI_METRIC_CATEGORY_CACHECUPTI_METRIC_CATEGORY_TEXTURECUPTI_METRIC_CATEGORY_NVLINK"
	_CUpti_MetricCategory_name_1 = "CUPTI_METRIC_CATEGORY_FORCE_INT"
)

var (
	_CUpti_MetricCategory_index_0 = [...]uint8{0, 28, 61, 97, 124, 153, 181}
	_CUpti_MetricCategory_index_1 = [...]uint8{0, 31}
)

func (i CUpti_MetricCategory) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _CUpti_MetricCategory_name_0[_CUpti_MetricCategory_index_0[i]:_CUpti_MetricCategory_index_0[i+1]]
	case i == 2147483647:
		return _CUpti_MetricCategory_name_1
	default:
		return fmt.Sprintf("CUpti_MetricCategory(%d)", i)
	}
}

var _CUpti_MetricCategoryNameToValue_map = map[string]CUpti_MetricCategory{
	_CUpti_MetricCategory_name_0[0:28]:    0,
	_CUpti_MetricCategory_name_0[28:61]:   1,
	_CUpti_MetricCategory_name_0[61:97]:   2,
	_CUpti_MetricCategory_name_0[97:124]:  3,
	_CUpti_MetricCategory_name_0[124:153]: 4,
	_CUpti_MetricCategory_name_0[153:181]: 5,
	_CUpti_MetricCategory_name_1[0:31]:    2147483647,
}

func CUpti_MetricCategoryString(s string) (CUpti_MetricCategory, error) {
	if val, ok := _CUpti_MetricCategoryNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_MetricCategory values", s)
}

func (i CUpti_MetricCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *CUpti_MetricCategory) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_MetricCategory should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_MetricCategoryString(s)
	return err
}
