// Code generated by "enumer -type=CUpti_ActivityPCSamplingPeriod -json -text -yaml -sql"; DO NOT EDIT.

//
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const (
	_CUpti_ActivityPCSamplingPeriodName_0 = "CUPTI_ACTIVITY_PC_SAMPLING_PERIOD_INVALIDCUPTI_ACTIVITY_PC_SAMPLING_PERIOD_MINCUPTI_ACTIVITY_PC_SAMPLING_PERIOD_LOWCUPTI_ACTIVITY_PC_SAMPLING_PERIOD_MIDCUPTI_ACTIVITY_PC_SAMPLING_PERIOD_HIGHCUPTI_ACTIVITY_PC_SAMPLING_PERIOD_MAX"
	_CUpti_ActivityPCSamplingPeriodName_1 = "CUPTI_ACTIVITY_PC_SAMPLING_PERIOD_FORCE_INT"
)

var (
	_CUpti_ActivityPCSamplingPeriodIndex_0 = [...]uint8{0, 41, 78, 115, 152, 190, 227}
	_CUpti_ActivityPCSamplingPeriodIndex_1 = [...]uint8{0, 43}
)

func (i CUpti_ActivityPCSamplingPeriod) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _CUpti_ActivityPCSamplingPeriodName_0[_CUpti_ActivityPCSamplingPeriodIndex_0[i]:_CUpti_ActivityPCSamplingPeriodIndex_0[i+1]]
	case i == 2147483647:
		return _CUpti_ActivityPCSamplingPeriodName_1
	default:
		return fmt.Sprintf("CUpti_ActivityPCSamplingPeriod(%d)", i)
	}
}

var _CUpti_ActivityPCSamplingPeriodValues = []CUpti_ActivityPCSamplingPeriod{0, 1, 2, 3, 4, 5, 2147483647}

var _CUpti_ActivityPCSamplingPeriodNameToValueMap = map[string]CUpti_ActivityPCSamplingPeriod{
	_CUpti_ActivityPCSamplingPeriodName_0[0:41]:    0,
	_CUpti_ActivityPCSamplingPeriodName_0[41:78]:   1,
	_CUpti_ActivityPCSamplingPeriodName_0[78:115]:  2,
	_CUpti_ActivityPCSamplingPeriodName_0[115:152]: 3,
	_CUpti_ActivityPCSamplingPeriodName_0[152:190]: 4,
	_CUpti_ActivityPCSamplingPeriodName_0[190:227]: 5,
	_CUpti_ActivityPCSamplingPeriodName_1[0:43]:    2147483647,
}

// CUpti_ActivityPCSamplingPeriodString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CUpti_ActivityPCSamplingPeriodString(s string) (CUpti_ActivityPCSamplingPeriod, error) {
	if val, ok := _CUpti_ActivityPCSamplingPeriodNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CUpti_ActivityPCSamplingPeriod values", s)
}

// CUpti_ActivityPCSamplingPeriodValues returns all values of the enum
func CUpti_ActivityPCSamplingPeriodValues() []CUpti_ActivityPCSamplingPeriod {
	return _CUpti_ActivityPCSamplingPeriodValues
}

// IsACUpti_ActivityPCSamplingPeriod returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CUpti_ActivityPCSamplingPeriod) IsACUpti_ActivityPCSamplingPeriod() bool {
	for _, v := range _CUpti_ActivityPCSamplingPeriodValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CUpti_ActivityPCSamplingPeriod
func (i CUpti_ActivityPCSamplingPeriod) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CUpti_ActivityPCSamplingPeriod
func (i *CUpti_ActivityPCSamplingPeriod) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CUpti_ActivityPCSamplingPeriod should be a string, got %s", data)
	}

	var err error
	*i, err = CUpti_ActivityPCSamplingPeriodString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CUpti_ActivityPCSamplingPeriod
func (i CUpti_ActivityPCSamplingPeriod) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CUpti_ActivityPCSamplingPeriod
func (i *CUpti_ActivityPCSamplingPeriod) UnmarshalText(text []byte) error {
	var err error
	*i, err = CUpti_ActivityPCSamplingPeriodString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for CUpti_ActivityPCSamplingPeriod
func (i CUpti_ActivityPCSamplingPeriod) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for CUpti_ActivityPCSamplingPeriod
func (i *CUpti_ActivityPCSamplingPeriod) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = CUpti_ActivityPCSamplingPeriodString(s)
	return err
}

func (i CUpti_ActivityPCSamplingPeriod) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *CUpti_ActivityPCSamplingPeriod) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := CUpti_ActivityPCSamplingPeriodString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
